# Generated by Django 5.0 on 2024-06-20 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokumen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('url', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LayananGajiBerkala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('belum', 'belum'), ('pengajuan', 'pengajuan'), ('proses', 'proses'), ('selesai', 'selesai')], default='belum', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayananKenaikanJabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('belum', 'belum'), ('pengajuan', 'pengajuan'), ('proses', 'proses'), ('selesai', 'selesai')], default='belum', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayananKenaikanPangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('belum', 'belum'), ('pengajuan', 'pengajuan'), ('proses', 'proses'), ('selesai', 'selesai')], default='belum', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayananPenerbitanPAK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('belum', 'belum'), ('pengajuan', 'pengajuan'), ('proses', 'proses'), ('selesai', 'selesai')], default='belum', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayananPengakuanGelar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk_tubel_ibel', models.FileField(blank=True, upload_to='tubel_ibel/sk/')),
                ('status', models.CharField(choices=[('belum', 'belum'), ('pengajuan', 'pengajuan'), ('proses', 'proses'), ('selesai', 'selesai')], default='belum', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayananSIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rekom_profesi', models.FileField(upload_to='layanan/sip/rekom_pofesi/')),
                ('rekom_faskes', models.FileField(upload_to='layanan/sip/rekom_faskes/')),
                ('pernyataan_praktik', models.FileField(upload_to='layanan/sip/praktik/')),
                ('ket_sehat', models.FileField(upload_to='layanan/sip/sehat/')),
                ('pasfoto', models.FileField(upload_to='layanan/sip/foto/')),
                ('status', models.CharField(choices=[('belum', 'belum'), ('pengajuan', 'pengajuan'), ('proses', 'proses'), ('selesai', 'selesai')], default='belum', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayananUsulanDiklat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justifikasi', models.TextField(blank=True)),
                ('brosur', models.FileField(blank=True, upload_to='diklat/brosur/')),
                ('tor', models.FileField(blank=True, upload_to='diklat/tor/')),
                ('status', models.CharField(choices=[('usulan', 'usulan'), ('tindaklanjut', 'tindaklanjut'), ('proses', 'proses'), ('selesai', 'selesai')], default='usulan', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayananUsulanInovasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('usulan', 'usulan'), ('tindaklanjut', 'tindaklanjut'), ('proses', 'proses'), ('selesai', 'selesai')], default='usulan', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KenaikanPangkatJabFungsional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mutasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatbekerja')),
                ('pak', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpak')),
                ('pendidikan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpendidikan')),
                ('pengangkatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpengangkatan')),
                ('sk_kp_terakhir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpanggol')),
            ],
        ),
        migrations.CreateModel(
            name='KenaikanPangkatJabPelaksana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mutasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatbekerja')),
                ('pendidikan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpendidikan')),
                ('pengangkatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpengangkatan')),
                ('sk_kp_terakhir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpanggol')),
            ],
        ),
        migrations.CreateModel(
            name='KenaikanPangkatJabStruktural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diklat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatdiklat')),
                ('mutasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatbekerja')),
                ('pendidikan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpendidikan')),
                ('pengangkatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpengangkatan')),
                ('sk_kp_terakhir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpanggol')),
            ],
        ),
        migrations.CreateModel(
            name='KinerjaKenaikanJabFung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinerja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatkinerja')),
            ],
        ),
        migrations.CreateModel(
            name='KinerjaKenaikanPangkatJabPelaksana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kenaikan_pangkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.kenaikanpangkatjabpelaksana')),
                ('kinerja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatkinerja')),
            ],
        ),
        migrations.AddField(
            model_name='kenaikanpangkatjabpelaksana',
            name='kinerja_dua_thn',
            field=models.ManyToManyField(through='layanan.KinerjaKenaikanPangkatJabPelaksana', to='dokumen.riwayatkinerja'),
        ),
        migrations.CreateModel(
            name='KinerjaKenaikanPangkatJafung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kenaikan_pangkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.kenaikanpangkatjabfungsional')),
                ('kinerja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatkinerja')),
            ],
        ),
        migrations.AddField(
            model_name='kenaikanpangkatjabfungsional',
            name='kinerja_dua_thn',
            field=models.ManyToManyField(blank=True, through='layanan.KinerjaKenaikanPangkatJafung', to='dokumen.riwayatkinerja'),
        ),
        migrations.CreateModel(
            name='KinerjaKenaikanPangkatStruktural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kenaikan_pangkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.kenaikanpangkatjabstruktural')),
                ('kinerja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatkinerja')),
            ],
        ),
        migrations.AddField(
            model_name='kenaikanpangkatjabstruktural',
            name='kinerja_dua_thn',
            field=models.ManyToManyField(through='layanan.KinerjaKenaikanPangkatStruktural', to='dokumen.riwayatkinerja'),
        ),
        migrations.CreateModel(
            name='LayananCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_jabatan', models.CharField(blank=True, choices=[('Jabatan Struktural', 'Jabatan Struktural'), ('Jabatan Fungsional', 'Jabatan Fungsional'), ('Jabatan Pelaksana', 'Jabatan Pelaksana')], max_length=25, verbose_name='Jenis Jabatan Saat Ini')),
                ('status', models.CharField(choices=[('belum', 'belum'), ('pengajuan', 'pengajuan'), ('proses', 'proses'), ('selesai', 'selesai')], default='belum', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuti', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dokumen.riwayatcuti', verbose_name='Riwayat Cuti')),
                ('layanan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.jenislayanan')),
            ],
        ),
    ]
