# Generated by Django 5.0 on 2024-06-20 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokumen', '0002_initial'),
        ('layanan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='layanancuti',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layanangajiberkala',
            name='berkala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berkala_saat_ini', to='dokumen.riwayatgajiberkala'),
        ),
        migrations.AddField(
            model_name='layanangajiberkala',
            name='layanan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.jenislayanan'),
        ),
        migrations.AddField(
            model_name='layanangajiberkala',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layanangajiberkala',
            name='riwayat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berkala_sebelum', to='dokumen.riwayatgajiberkala'),
        ),
        migrations.AddField(
            model_name='layanankenaikanjabatan',
            name='jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatjabatan'),
        ),
        migrations.AddField(
            model_name='layanankenaikanjabatan',
            name='kinerja_dua_thn',
            field=models.ManyToManyField(through='layanan.KinerjaKenaikanJabFung', to='dokumen.riwayatkinerja'),
        ),
        migrations.AddField(
            model_name='layanankenaikanjabatan',
            name='kompetensi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.ujikompetensi'),
        ),
        migrations.AddField(
            model_name='layanankenaikanjabatan',
            name='layanan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.jenislayanan'),
        ),
        migrations.AddField(
            model_name='layanankenaikanjabatan',
            name='pak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpak'),
        ),
        migrations.AddField(
            model_name='layanankenaikanjabatan',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kinerjakenaikanjabfung',
            name='kenaikan_jabatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.layanankenaikanjabatan'),
        ),
        migrations.AddField(
            model_name='layanankenaikanpangkat',
            name='jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatjabatan'),
        ),
        migrations.AddField(
            model_name='layanankenaikanpangkat',
            name='layanan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.jenislayanan'),
        ),
        migrations.AddField(
            model_name='layanankenaikanpangkat',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kenaikanpangkatjabstruktural',
            name='jenis_kp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.layanankenaikanpangkat'),
        ),
        migrations.AddField(
            model_name='kenaikanpangkatjabpelaksana',
            name='jenis_kp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.layanankenaikanpangkat'),
        ),
        migrations.AddField(
            model_name='kenaikanpangkatjabfungsional',
            name='jenis_kp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.layanankenaikanpangkat'),
        ),
        migrations.AddField(
            model_name='layananpenerbitanpak',
            name='kinerja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatkinerja'),
        ),
        migrations.AddField(
            model_name='layananpenerbitanpak',
            name='layanan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.jenislayanan'),
        ),
        migrations.AddField(
            model_name='layananpenerbitanpak',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layananpengakuangelar',
            name='layanan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.jenislayanan'),
        ),
        migrations.AddField(
            model_name='layananpengakuangelar',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layananpengakuangelar',
            name='pendidikan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokumen.riwayatpendidikan'),
        ),
        migrations.AddField(
            model_name='layanansip',
            name='ijazah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpendidikan'),
        ),
        migrations.AddField(
            model_name='layanansip',
            name='layanan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.jenislayanan'),
        ),
        migrations.AddField(
            model_name='layanansip',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layanansip',
            name='str_profesi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatprofesi'),
        ),
        migrations.AddField(
            model_name='layananusulandiklat',
            name='diklat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokumen.riwayatdiklat'),
        ),
        migrations.AddField(
            model_name='layananusulandiklat',
            name='layanan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.jenislayanan'),
        ),
        migrations.AddField(
            model_name='layananusulandiklat',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layananusulaninovasi',
            name='inovasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokumen.riwayatinovasi'),
        ),
        migrations.AddField(
            model_name='layananusulaninovasi',
            name='layanan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.jenislayanan'),
        ),
        migrations.AddField(
            model_name='layananusulaninovasi',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
