# Generated by Django 5.0 on 2024-07-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layananusulandiklat',
            name='bukti_lunas',
            field=models.FileField(blank=True, upload_to='diklat/kwitansi/'),
        ),
        migrations.AddField(
            model_name='layananusulandiklat',
            name='spt',
            field=models.FileField(blank=True, upload_to='diklat/spt/'),
        ),
        migrations.AlterField(
            model_name='layanancuti',
            name='jenis_jabatan',
            field=models.CharField(blank=True, choices=[('Struktural', 'Struktural'), ('Fungsional', 'Fungsional'), ('Pelaksana', 'Pelaksana')], max_length=25, verbose_name='Jenis Jabatan Saat Ini'),
        ),
        migrations.AlterField(
            model_name='layananusulaninovasi',
            name='status',
            field=models.CharField(choices=[('usulan', 'usulan'), ('proses', 'proses'), ('tidak ditindaklanjut', 'tidak ditindaklanjut'), ('tindaklanjut', 'tindaklanjut'), ('selesai', 'selesai')], default='usulan', max_length=20),
        ),
    ]
