# Generated by Django 5.0 on 2024-07-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0003_layananusulandiklat_bukti_lunas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layananusulandiklat',
            name='status',
            field=models.CharField(choices=[('usulan', 'usulan'), ('proses', 'proses'), ('tidak ditindaklanjut', 'tidak ditindaklanjut'), ('tindaklanjut', 'tindaklanjut'), ('selesai', 'selesai')], default='usulan', max_length=50),
        ),
    ]
