# Generated by Django 5.0 on 2024-07-21 20:12

import layanan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0004_alter_layananusulandiklat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanancuti',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layanangajiberkala',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layananusulandiklat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layananusulaninovasi',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='layanancuti',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('pengajuan', 'pengajuan'), ('tidak ditindaklanjut', 'tidak ditindaklanjut'), ('tindaklanjut', 'tindaklanjut'), ('selesai', 'selesai')], max_length=50),
        ),
        migrations.AlterField(
            model_name='layananpengakuangelar',
            name='sk_tubel_ibel',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='tubel_ibel/sk/', validators=[layanan.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='layanansip',
            name='ket_sehat',
            field=models.FileField(help_text='Ukuran maksimal file 2.5MB', upload_to='layanan/sip/sehat/', validators=[layanan.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='layanansip',
            name='pasfoto',
            field=models.FileField(help_text='Ukuran maksimal file 2.5MB', upload_to='layanan/sip/foto/', validators=[layanan.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='layanansip',
            name='pernyataan_praktik',
            field=models.FileField(help_text='Ukuran maksimal file 2.5MB', upload_to='layanan/sip/praktik/', validators=[layanan.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='layanansip',
            name='rekom_faskes',
            field=models.FileField(help_text='Ukuran maksimal file 2.5MB', upload_to='layanan/sip/rekom_faskes/', validators=[layanan.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='layanansip',
            name='rekom_profesi',
            field=models.FileField(help_text='Ukuran maksimal file 2.5MB', upload_to='layanan/sip/rekom_pofesi/', validators=[layanan.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='layananusulandiklat',
            name='brosur',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='diklat/brosur/', validators=[layanan.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='layananusulandiklat',
            name='bukti_lunas',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='diklat/kwitansi/', validators=[layanan.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='layananusulandiklat',
            name='spt',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='diklat/spt/', validators=[layanan.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='layananusulandiklat',
            name='tor',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='diklat/tor/', validators=[layanan.models.validate_file_size]),
        ),
    ]
