# Generated by Django 5.0 on 2024-08-05 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0005_layanancuti_is_read_layanangajiberkala_is_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifikasiCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persetujuan1', models.BooleanField(default=False)),
                ('catatan1', models.TextField(blank=True)),
                ('persetujuan2', models.BooleanField(default=False)),
                ('catatan2', models.TextField(blank=True)),
                ('persetujuan3', models.BooleanField(default=False)),
                ('catatan3', models.TextField(blank=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layanan_cuti', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='layanan.layanancuti')),
                ('verifikator1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikator1_cuti', to=settings.AUTH_USER_MODEL)),
                ('verifikator2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikator2_cuti', to=settings.AUTH_USER_MODEL)),
                ('verifikator3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikator3_cuti', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
