# Generated by Django 5.0 on 2024-08-13 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0006_verifikasicuti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SumberPembiayaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='layananusulandiklat',
            name='pembiayaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.sumberpembiayaan'),
        ),
        migrations.CreateModel(
            name='VerifikasiDiklat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persetujuan1', models.BooleanField(default=False)),
                ('catatan1', models.TextField(blank=True)),
                ('persetujuan2', models.BooleanField(default=False)),
                ('catatan2', models.TextField(blank=True)),
                ('persetujuan3', models.BooleanField(default=False)),
                ('catatan3', models.TextField(blank=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layanan_diklat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='layanan.layananusulandiklat')),
                ('verifikator1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikator1_diklat', to=settings.AUTH_USER_MODEL)),
                ('verifikator2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikator2_diklat', to=settings.AUTH_USER_MODEL)),
                ('verifikator3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikator3_diklat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
