# Generated by Django 5.0 on 2024-08-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0007_sumberpembiayaan_layananusulandiklat_pembiayaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layananusulandiklat',
            name='biaya',
            field=models.FloatField(blank=True, null=True, verbose_name='Jumlah Biaya'),
        ),
    ]
