# Generated by Django 5.0 on 2025-01-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0008_layananusulandiklat_biaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanancuti',
            name='cuti_tunda',
            field=models.BooleanField(default=False),
        ),
    ]
