# Generated by Django 5.0 on 2025-02-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0009_layanancuti_cuti_tunda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layananusulandiklat',
            name='diklat',
        ),
        migrations.RemoveField(
            model_name='layananusulandiklat',
            name='pegawai',
        ),
    ]
