# Generated by Django 5.0 on 2025-04-10 03:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0010_remove_layananusulandiklat_diklat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layananusulandiklat',
            name='catatan_sdm',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='layananusulandiklat',
            name='justifikasi',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
