# Generated by Django 5.0 on 2025-07-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0011_layananusulandiklat_catatan_sdm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanancuti',
            name='tahun',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tahun Cuti'),
        ),
    ]
