# Generated by Django 5.0 on 2025-07-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0012_layanancuti_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanancuti',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('pengajuan', 'pengajuan'), ('tidak ditindaklanjut', 'tidak ditindaklanjut'), ('tindaklanjut', 'tindaklanjut'), ('selesai', 'selesai')], default='draft', max_length=50, verbose_name='Status Cuti'),
        ),
    ]
