# Generated by Django 5.0 on 2025-07-31 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0013_alter_layanancuti_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layanancuti',
            name='cuti',
        ),
    ]
