# Generated by Django 5.0 on 2025-12-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0014_remove_layanancuti_cuti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifikasicuti',
            name='persetujuan1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verifikasicuti',
            name='persetujuan2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verifikasicuti',
            name='persetujuan3',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
