# Generated by Django 5.0 on 2025-12-11 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0022_riwayatcuti_status_persetujuan'),
        ('layanan', '0015_alter_verifikasicuti_persetujuan1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PelimpahanTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_tugas', models.TextField(help_text='Ringkasan tugas yang dilimpahkan selama pegawai cuti.')),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft (disusun pemberi tugas)'), ('menunggu_penerima', 'Menunggu persetujuan penerima'), ('ditolak_penerima', 'Ditolak penerima tugas'), ('menunggu_kepala', 'Menunggu persetujuan Kepala Instalasi'), ('disetujui', 'Disetujui Kepala Instalasi'), ('ditolak_kepala', 'Ditolak Kepala Instalasi')], default='draft', max_length=30)),
                ('persetujuan_penerima', models.CharField(choices=[('belum', 'Belum diputuskan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='belum', max_length=20)),
                ('catatan_penerima', models.TextField(blank=True)),
                ('persetujuan_kepala', models.CharField(choices=[('belum', 'Belum diputuskan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='belum', max_length=20)),
                ('catatan_kepala', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kepala_instalasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelimpahan_disetujui', to=settings.AUTH_USER_MODEL)),
                ('pemberi_tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelimpahan_dibuat', to=settings.AUTH_USER_MODEL)),
                ('penerima_tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelimpahan_diterima', to=settings.AUTH_USER_MODEL)),
                ('riwayat_cuti', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pelimpahan_tugas', to='dokumen.riwayatcuti')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
