# Generated by Django 5.0 on 2025-12-15 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0016_pelimpahantugas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelimpahantugas',
            old_name='catatan_kepala',
            new_name='catatan_atasan',
        ),
        migrations.RenameField(
            model_name='pelimpahantugas',
            old_name='persetujuan_kepala',
            new_name='persetujuan_atasan',
        ),
        migrations.RemoveField(
            model_name='pelimpahantugas',
            name='kepala_instalasi',
        ),
        migrations.AddField(
            model_name='pelimpahantugas',
            name='atasan_penyetuju',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelimpahan_disetujui_atasan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pelimpahantugas',
            name='deskripsi_tugas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pelimpahantugas',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('menunggu_penerima', 'Menunggu persetujuan penerima'), ('ditolak_penerima', 'Ditolak penerima'), ('menunggu_atasan', 'Menunggu persetujuan atasan (khusus level instalasi)'), ('ditolak_atasan', 'Ditolak atasan'), ('disetujui', 'Disetujui')], default='draft', max_length=30),
        ),
    ]
