# Generated by Django 5.0 on 2025-12-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0017_rename_catatan_kepala_pelimpahantugas_catatan_atasan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifikasicuti',
            name='keputusan1',
            field=models.CharField(choices=[('belum', 'Belum diputuskan'), ('setuju', 'Disetujui'), ('tunda', 'Ditunda'), ('tolak', 'Ditolak')], default='belum', max_length=10),
        ),
        migrations.AddField(
            model_name='verifikasicuti',
            name='keputusan2',
            field=models.CharField(choices=[('belum', 'Belum diputuskan'), ('setuju', 'Disetujui'), ('tunda', 'Ditunda'), ('tolak', 'Ditolak')], default='belum', max_length=10),
        ),
        migrations.AddField(
            model_name='verifikasicuti',
            name='keputusan3',
            field=models.CharField(choices=[('belum', 'Belum diputuskan'), ('setuju', 'Disetujui'), ('tunda', 'Ditunda'), ('tolak', 'Ditolak')], default='belum', max_length=10),
        ),
    ]
