# Generated by Django 5.0 on 2026-07-10 08:17

import django.db.models.deletion
import layanan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0018_verifikasicuti_keputusan1_verifikasicuti_keputusan2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layanansip',
            name='ket_sehat',
        ),
        migrations.RemoveField(
            model_name='layanansip',
            name='pasfoto',
        ),
        migrations.RemoveField(
            model_name='layanansip',
            name='pernyataan_praktik',
        ),
        migrations.RemoveField(
            model_name='layanansip',
            name='rekom_faskes',
        ),
        migrations.RemoveField(
            model_name='layanansip',
            name='rekom_profesi',
        ),
        migrations.AddField(
            model_name='layanansip',
            name='is_foto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layanansip',
            name='is_ktp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layanansip',
            name='kecukupan_skp',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='layanan/sip/kecukupan_skp/', validators=[layanan.models.validate_file_size]),
        ),
        migrations.CreateModel(
            name='PengajuanSIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('belum', 'belum'), ('pengajuan', 'pengajuan'), ('proses', 'proses'), ('selesai', 'selesai')], default='pengajuan', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.layanansip')),
            ],
        ),
    ]
