# Generated by Django 5.0 on 2026-07-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0019_remove_layanansip_ket_sehat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PengajuanSIP',
        ),
    ]
