# Generated by Django 5.0 on 2026-07-11 15:12

import layanan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0021_layanansip_surat_rekomendasi_skp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layanansip',
            name='surat_rekomendasi_skp',
        ),
        migrations.AddField(
            model_name='layanansip',
            name='surat_rekomendasi_sip',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='layanan/sip/rekomendasi_sip/', validators=[layanan.models.validate_file_size], verbose_name='Surat Rekomendasi SIP yang Ditandatangani Pimpinan'),
        ),
    ]
