# Generated by Django 5.0 on 2026-07-14 11:12

import layanan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0022_remove_layanansip_surat_rekomendasi_skp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanansip',
            name='surat_permohonan_rekomendasi',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='layanan/sip/rekomendasi_sip/', validators=[layanan.models.validate_file_size], verbose_name='Surat Permohonan Rekomendasi SIP yang sudah ditandatangani dan bermeterai'),
        ),
    ]
