# Generated by Django 5.0 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0023_layanansip_surat_permohonan_rekomendasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanansip',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
