# Generated by Django 5.0 on 2026-07-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0024_layanansip_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanangajiberkala',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum diproses'), ('pengajuan', 'Pengajuan'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='belum', max_length=50),
        ),
        migrations.AlterField(
            model_name='layanankenaikanjabatan',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum diproses'), ('pengajuan', 'Pengajuan'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='belum', max_length=50),
        ),
        migrations.AlterField(
            model_name='layanankenaikanpangkat',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum diproses'), ('pengajuan', 'Pengajuan'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='belum', max_length=50),
        ),
        migrations.AlterField(
            model_name='layananpenerbitanpak',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum diproses'), ('pengajuan', 'Pengajuan'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='belum', max_length=50),
        ),
        migrations.AlterField(
            model_name='layananpengakuangelar',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum diproses'), ('pengajuan', 'Pengajuan'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='belum', max_length=50),
        ),
        migrations.AlterField(
            model_name='layanansip',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum diproses'), ('pengajuan', 'Pengajuan'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='belum', max_length=50),
        ),
    ]
