# Generated by Django 5.0 on 2026-07-15 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0026_riwayatpendidikan_file_verifikasi_and_more'),
        ('layanan', '0025_alter_layanangajiberkala_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LayananPengakuanGelar',
            new_name='LayananPencantumanGelar',
        ),
        migrations.RemoveField(
            model_name='kinerjakenaikanpangkatjafung',
            name='kenaikan_pangkat',
        ),
        migrations.RemoveField(
            model_name='kenaikanpangkatjabpelaksana',
            name='jenis_kp',
        ),
        migrations.RemoveField(
            model_name='kenaikanpangkatjabpelaksana',
            name='kinerja_dua_thn',
        ),
        migrations.RemoveField(
            model_name='kenaikanpangkatjabpelaksana',
            name='mutasi',
        ),
        migrations.RemoveField(
            model_name='kenaikanpangkatjabpelaksana',
            name='pendidikan',
        ),
        migrations.RemoveField(
            model_name='kenaikanpangkatjabpelaksana',
            name='pengangkatan',
        ),
        migrations.RemoveField(
            model_name='kenaikanpangkatjabpelaksana',
            name='sk_kp_terakhir',
        ),
        migrations.RemoveField(
            model_name='kinerjakenaikanpangkatjabpelaksana',
            name='kenaikan_pangkat',
        ),
        migrations.RemoveField(
            model_name='kenaikanpangkatjabstruktural',
            name='diklat',
        ),
        migrations.RemoveField(
            model_name='kenaikanpangkatjabstruktural',
            name='jenis_kp',
        ),
        migrations.RemoveField(
            model_name='kenaikanpangkatjabstruktural',
            name='kinerja_dua_thn',
        ),
        migrations.RemoveField(
            model_name='kenaikanpangkatjabstruktural',
            name='mutasi',
        ),
        migrations.RemoveField(
            model_name='kenaikanpangkatjabstruktural',
            name='pendidikan',
        ),
        migrations.RemoveField(
            model_name='kenaikanpangkatjabstruktural',
            name='pengangkatan',
        ),
        migrations.RemoveField(
            model_name='kenaikanpangkatjabstruktural',
            name='sk_kp_terakhir',
        ),
        migrations.RemoveField(
            model_name='kinerjakenaikanpangkatstruktural',
            name='kenaikan_pangkat',
        ),
        migrations.RemoveField(
            model_name='kinerjakenaikanjabfung',
            name='kenaikan_jabatan',
        ),
        migrations.RemoveField(
            model_name='kinerjakenaikanjabfung',
            name='kinerja',
        ),
        migrations.RemoveField(
            model_name='layanankenaikanjabatan',
            name='kinerja_dua_thn',
        ),
        migrations.RemoveField(
            model_name='kinerjakenaikanpangkatjabpelaksana',
            name='kinerja',
        ),
        migrations.RemoveField(
            model_name='kinerjakenaikanpangkatjafung',
            name='kinerja',
        ),
        migrations.RemoveField(
            model_name='kinerjakenaikanpangkatstruktural',
            name='kinerja',
        ),
        migrations.RemoveField(
            model_name='layanankenaikanjabatan',
            name='jabatan',
        ),
        migrations.RemoveField(
            model_name='layanankenaikanjabatan',
            name='kompetensi',
        ),
        migrations.RemoveField(
            model_name='layanankenaikanjabatan',
            name='layanan',
        ),
        migrations.RemoveField(
            model_name='layanankenaikanjabatan',
            name='pak',
        ),
        migrations.RemoveField(
            model_name='layanankenaikanjabatan',
            name='pegawai',
        ),
        migrations.RemoveField(
            model_name='layanankenaikanpangkat',
            name='jabatan',
        ),
        migrations.RemoveField(
            model_name='layanankenaikanpangkat',
            name='layanan',
        ),
        migrations.RemoveField(
            model_name='layanankenaikanpangkat',
            name='pegawai',
        ),
        migrations.RemoveField(
            model_name='layananpenerbitanpak',
            name='kinerja',
        ),
        migrations.RemoveField(
            model_name='layananpenerbitanpak',
            name='layanan',
        ),
        migrations.RemoveField(
            model_name='layananpenerbitanpak',
            name='pegawai',
        ),
        migrations.CreateModel(
            name='LayananNaikJabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('belum', 'Belum diproses'), ('pengajuan', 'Pengajuan'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='belum', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kinerja_dua_thn', models.ManyToManyField(blank=True, to='dokumen.riwayatkinerja')),
                ('kompetensi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.ujikompetensi')),
                ('layanan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.jenislayanan')),
                ('pak', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpak')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pendidikan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpendidikan')),
                ('str_profesi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatprofesi')),
            ],
        ),
        migrations.CreateModel(
            name='LayananNaikPangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kinerja_dua_thn', models.ManyToManyField(blank=True, to='dokumen.riwayatkinerja')),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.jenislayanan')),
                ('mutasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatbekerja')),
                ('pak', models.ManyToManyField(blank=True, help_text='Khusus Pejabat Fungsional', null=True, to='dokumen.riwayatpak')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pendidikan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpendidikan')),
                ('pengangkatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpengangkatan')),
                ('sk_jabfung', models.ForeignKey(help_text='Khusus Pejabat Fungsional', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatjabatan')),
                ('sk_kp_terakhir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpanggol')),
            ],
        ),
        migrations.DeleteModel(
            name='KenaikanPangkatJabFungsional',
        ),
        migrations.DeleteModel(
            name='KenaikanPangkatJabPelaksana',
        ),
        migrations.DeleteModel(
            name='KenaikanPangkatJabStruktural',
        ),
        migrations.DeleteModel(
            name='KinerjaKenaikanJabFung',
        ),
        migrations.DeleteModel(
            name='KinerjaKenaikanPangkatJabPelaksana',
        ),
        migrations.DeleteModel(
            name='KinerjaKenaikanPangkatJafung',
        ),
        migrations.DeleteModel(
            name='KinerjaKenaikanPangkatStruktural',
        ),
        migrations.DeleteModel(
            name='LayananKenaikanJabatan',
        ),
        migrations.DeleteModel(
            name='LayananKenaikanPangkat',
        ),
        migrations.DeleteModel(
            name='LayananPenerbitanPAK',
        ),
    ]
