# Generated by Django 5.0 on 2026-07-15 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0027_riwayatjabatan_usulan_riwayatpanggol_usulan'),
        ('layanan', '0026_rename_layananpengakuangelar_layananpencantumangelar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanannaikpangkat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layanannaikpangkat',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum diproses'), ('pengajuan', 'Pengajuan'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='pengajuan', max_length=50),
        ),
        migrations.AlterField(
            model_name='layanannaikpangkat',
            name='mutasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatbekerja'),
        ),
        migrations.AlterField(
            model_name='layanannaikpangkat',
            name='pak',
            field=models.ManyToManyField(blank=True, help_text='Khusus Pejabat Fungsional', to='dokumen.riwayatpak'),
        ),
        migrations.AlterField(
            model_name='layanannaikpangkat',
            name='sk_jabfung',
            field=models.ForeignKey(blank=True, help_text='Khusus Pejabat Fungsional', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatjabatan'),
        ),
    ]
