# Generated by Django 5.0 on 2026-07-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0028_create_jenis_layanan_pangkat'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanannaikjabatan',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='layanannaikjabatan',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum diproses'), ('pengajuan', 'Pengajuan'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='pengajuan', max_length=50),
        ),
    ]
