# Generated by Django 5.0 on 2026-07-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0031_deduplicate_jenis_layanan_and_unique_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanannaikjabatan',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum diproses'), ('pengajuan', 'Pengajuan'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='belum', max_length=50),
        ),
        migrations.AlterField(
            model_name='layanannaikpangkat',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum diproses'), ('pengajuan', 'Pengajuan'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='belum', max_length=50),
        ),
    ]
