# Generated by Django 5.0 on 2026-07-20 14:43

from django.db import migrations, models


def snapshot_existing_delegation_requirement(apps, schema_editor):
    PelimpahanTugas = apps.get_model('layanan', 'PelimpahanTugas')
    PelimpahanTugas.objects.filter(
        atasan_penyetuju__isnull=False
    ).update(butuh_persetujuan_atasan=True)
    PelimpahanTugas.objects.filter(
        atasan_penyetuju__isnull=True
    ).update(butuh_persetujuan_atasan=False)


def clear_delegation_requirement_snapshot(apps, schema_editor):
    apps.get_model('layanan', 'PelimpahanTugas').objects.update(
        butuh_persetujuan_atasan=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0032_alter_layanannaikjabatan_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelimpahantugas',
            name='butuh_persetujuan_atasan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verifikasicuti',
            name='diputuskan_pada1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verifikasicuti',
            name='diputuskan_pada2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verifikasicuti',
            name='diputuskan_pada3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            snapshot_existing_delegation_requirement,
            clear_delegation_requirement_snapshot,
        ),
    ]
