# Generated by Django 5.0 on 2026-07-20 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0033_alter_riwayatcuti_status_cuti'),
        ('layanan', '0033_pelimpahantugas_butuh_persetujuan_atasan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerubahanJadwalCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_perubahan', models.CharField(choices=[('langsung', 'Perubahan sebelum verifikasi'), ('revisi_proses', 'Revisi saat verifikasi berjalan'), ('perubahan_final', 'Perubahan setelah persetujuan final')], max_length=20)),
                ('status', models.CharField(choices=[('menunggu_verifikasi', 'Menunggu verifikasi perubahan'), ('menunggu_pelimpahan', 'Menunggu persetujuan ulang pelimpahan'), ('diterapkan', 'Perubahan diterapkan'), ('ditolak', 'Perubahan ditolak'), ('dibatalkan', 'Dibatalkan pemohon')], default='menunggu_verifikasi', max_length=25)),
                ('tanggal_mulai_lama', models.DateField()),
                ('tanggal_akhir_lama', models.DateField()),
                ('lama_cuti_lama', models.PositiveSmallIntegerField()),
                ('tanggal_mulai_baru', models.DateField()),
                ('tanggal_akhir_baru', models.DateField()),
                ('lama_cuti_baru', models.PositiveSmallIntegerField()),
                ('alasan', models.TextField()),
                ('snapshot_verifikasi', models.JSONField(blank=True, default=dict)),
                ('snapshot_pelimpahan', models.JSONField(blank=True, default=dict)),
                ('keputusan1', models.CharField(choices=[('belum', 'Belum diputuskan'), ('setuju', 'Disetujui'), ('tunda', 'Ditunda'), ('tolak', 'Ditolak')], default='belum', max_length=10)),
                ('catatan1', models.TextField(blank=True)),
                ('diputuskan_pada1', models.DateTimeField(blank=True, null=True)),
                ('keputusan2', models.CharField(choices=[('belum', 'Belum diputuskan'), ('setuju', 'Disetujui'), ('tunda', 'Ditunda'), ('tolak', 'Ditolak')], default='belum', max_length=10)),
                ('catatan2', models.TextField(blank=True)),
                ('diputuskan_pada2', models.DateTimeField(blank=True, null=True)),
                ('keputusan3', models.CharField(choices=[('belum', 'Belum diputuskan'), ('setuju', 'Disetujui'), ('tunda', 'Ditunda'), ('tolak', 'Ditolak')], default='belum', max_length=10)),
                ('catatan3', models.TextField(blank=True)),
                ('diputuskan_pada3', models.DateTimeField(blank=True, null=True)),
                ('diterapkan_pada', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diajukan_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perubahan_jadwal_cuti_diajukan', to=settings.AUTH_USER_MODEL)),
                ('riwayat_cuti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perubahan_jadwal', to='dokumen.riwayatcuti')),
                ('verifikator1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikator1_perubahan_jadwal_cuti', to=settings.AUTH_USER_MODEL)),
                ('verifikator2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikator2_perubahan_jadwal_cuti', to=settings.AUTH_USER_MODEL)),
                ('verifikator3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikator3_perubahan_jadwal_cuti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
