# Generated by Django 5.0 on 2026-07-25 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0036_remove_legacy_cuti_tertunda'),
        ('layanan', '0038_layanancuti_snapshot_saldo_cuti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanancuti',
            name='status',
            field=models.CharField(choices=[('pengajuan', 'Diajukan'), ('tindaklanjut', 'Sedang diverifikasi'), ('disetujui', 'Disetujui'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak'), ('dibatalkan', 'Dibatalkan')], default='pengajuan', max_length=20, verbose_name='Status Pengajuan Cuti'),
        ),
        migrations.CreateModel(
            name='PemutihanCutiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(choices=[('disetujui', 'Disetujui'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak'), ('dibatalkan', 'Dibatalkan')], max_length=20)),
                ('status_pengajuan_sebelum', models.CharField(max_length=20)),
                ('status_pengajuan_sesudah', models.CharField(max_length=20)),
                ('status_pelaksanaan_sebelum', models.CharField(blank=True, max_length=20)),
                ('status_pelaksanaan_sesudah', models.CharField(blank=True, max_length=20)),
                ('catatan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pemutihan_cuti_dilakukan', to=settings.AUTH_USER_MODEL)),
                ('layanan_cuti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_pemutihan', to='layanan.layanancuti')),
                ('riwayat_cuti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_pemutihan', to='dokumen.riwayatcuti')),
            ],
            options={
                'verbose_name': 'Log Pemutihan Cuti',
                'verbose_name_plural': 'Log Pemutihan Cuti',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
