from django.urls import path
from django.views.generic import RedirectView

from .views import (
    JenisLayananView,
    LayananCutiVerifikasiView,
    RiwayatLayananCutiView,
    RiwayatCutiBawahanView,
    LayananCutiCreateView,
    LayananCutiDetailView,
    UploadFileCutiView,
    PerubahanJadwalCutiCreateView,
    PerubahanJadwalCutiCancelView,
    PerubahanJadwalCutiVerifikasiView,
    LayananCutiUpdateView,
    LayananCutiDeleteView,
    CutiPemutihanAdminView,
    PolaKerjaPegawaiListCreateView,
    PolaKerjaPegawaiUpdateView,
    AdminOverrideKlaimTundaForCutiView,
    PelimpahanTugasCreateView,
    PelimpahanTugasPenerimaListView,
    PelimpahanTugasPenerimaUpdateView,
    PelimpahanKepalaListView,
    PelimpahanTugasAtasanUpdateView,
    PelimpahanTugasDetailView,
    PengalihanPelimpahanTugasView,
    
    BerkalaListView,
    createlayananberkala,
    LayananGajiBerkalaUpdateView,
    LayananGajiBerkalaAdminView,
    LayananGajiBerkalaAdminAddView,
    LayananGajiBerkalaUpload,
    
    LayananUsulanDiklatView,
    LayananUsulanDiklatStaffView,
    LayananUsulanDiklatListView,
    LayananUsulanDiklatCreateView,
    LayananUsulanDiklatUpdateView,
    PenugasanDiklatCreateView,
    PengalihanDiklatCreateView,
    VerifikasiDiklatView,
    CatatanSDMUsulanLayananDiklatUpdateView,
    LayananUsulanInovasiView,
    LayananUsulanInovasiUpdateView,
    NotifikasiView,
    LayananSIPListView,
    LayananSIPCreateView,
    LayananSIPDetailView,
    LayananSIPUpdateView,
    LayananSIPUploadRekomendasiView,
    LayananSIPUploadPersyaratanView,
    LayananNaikPangkatListView,
    LayananNaikPangkatCreateView,
    LayananNaikPangkatUpdateView,
    LayananNaikPangkatDetailView,
    LayananNaikPangkatProcessView,
    LayananNaikJabatanListView,
    LayananNaikJabatanCreateView,
    LayananNaikJabatanUpdateView,
    LayananNaikJabatanDetailView,
    LayananNaikJabatanProcessView,
    SuratUsulanJabatanView,
    PromotionSupportingOptionsView,
)


urlpatterns=[
    path('', JenisLayananView.as_view(), name='layanan_view'),
    path('layanan-cuti/', RiwayatLayananCutiView.as_view(), name='layanan_cuti_listview'),
    path('layanan-cuti-bawahan/', RiwayatCutiBawahanView.as_view(), name='layanan_cuti_bawahan_listview'),
    path("layanan-cuti/<int:id>/verifikasi/", LayananCutiVerifikasiView.as_view(), name="layanan_cuti_verifikasi"),
    path('layanan-cuti/create/', LayananCutiCreateView.as_view(), name='layanan_cuti_create_view'),
    path("layanan-cuti/<int:pk>/detail/", LayananCutiDetailView.as_view(), name="layanan_cuti_detail"),
    path(
        "layanan-cuti/riwayat/<int:pk>/upload-surat/",
        UploadFileCutiView.as_view(),
        name="upload_file_cuti",
    ),
    path(
        'layanan-cuti/riwayat/<int:riwayat_pk>/ubah-jadwal/',
        PerubahanJadwalCutiCreateView.as_view(),
        name='perubahan_jadwal_cuti_create',
    ),
    path(
        'layanan-cuti/perubahan-jadwal/<int:pk>/verifikasi/',
        PerubahanJadwalCutiVerifikasiView.as_view(),
        name='perubahan_jadwal_cuti_verifikasi',
    ),
    path(
        'layanan-cuti/perubahan-jadwal/<int:pk>/batalkan/',
        PerubahanJadwalCutiCancelView.as_view(),
        name='perubahan_jadwal_cuti_cancel',
    ),
    path('layanan-cuti/<int:pk>/delete/', LayananCutiDeleteView.as_view(), name='layanan_cuti_delete'),
    path(
        'layanan-cuti/pemutihan/',
        CutiPemutihanAdminView.as_view(),
        name='cuti_pemutihan_admin',
    ),
    path(
        'layanan-cuti/pola-kerja/',
        PolaKerjaPegawaiListCreateView.as_view(),
        name='pola_kerja_pegawai',
    ),
    path(
        'layanan-cuti/pola-kerja/<int:pk>/ubah/',
        PolaKerjaPegawaiUpdateView.as_view(),
        name='pola_kerja_pegawai_update',
    ),
    path('pelimpahan-tugas/<int:riwayat_pk>/create/', PelimpahanTugasCreateView.as_view(), name='pelimpahan_create'),
    path("layanan-cuti/<int:riwayat_id>/override-klaim-tunda/", AdminOverrideKlaimTundaForCutiView.as_view(),name="cuti_override_klaim_tunda"),
    path('pelimpahan-tugas/penerima-list/', PelimpahanTugasPenerimaListView.as_view(), name='pelimpahan_penerima_list'),
    path('pelimpahan-tugas/<int:pk>/detail/', PelimpahanTugasDetailView.as_view(), name='pelimpahan_detail'),
    path('pelimpahan-tugas/<int:pk>/alihkan/', PengalihanPelimpahanTugasView.as_view(), name='pelimpahan_alihkan'),
    path('pelimpahan-tugas/penerima-list/<int:pk>/update/', PelimpahanTugasPenerimaUpdateView.as_view(), name='pelimpahan_penerima_update'),
    path('pelimpahan-tugas/kepala-list/', PelimpahanKepalaListView.as_view(), name='pelimpahan_atasan_list'),
    path('pelimpahan-tugas/kepala-list/<int:pk>/update/', PelimpahanTugasAtasanUpdateView.as_view(), name='pelimpahan_atasan_update'),
    path(
        'yancuti/<str:status>/',
        RedirectView.as_view(url='/layanan/layanan-cuti/', permanent=False),
        name='layanan_cuti_view',
    ),
    path('yancuti/<str:status>/<int:id>/', LayananCutiUpdateView.as_view(), name='layanan_cuti_update_view'),
    path(
        'pengajuan-cuti/',
        RedirectView.as_view(pattern_name='layanan_urls:layanan_cuti_create_view', permanent=False),
        name='pengajuan_cuti_view',
    ),
    path(
        'list-cuti-tunda/',
        RedirectView.as_view(pattern_name='layanan_urls:layanan_cuti_create_view', permanent=False),
        name='layanan_cuti_tunda_view',
    ),
    path(
        'cuti-tunda/<int:pk>/',
        RedirectView.as_view(url='/layanan/layanan-cuti/create/', permanent=False),
        name='layanan_ambil_cuti_tunda_view',
    ),
    path(
        'update-cuti-tunda/<int:pk>/',
        RedirectView.as_view(url='/layanan/layanan-cuti/', permanent=False),
        name='layanan_update_cuti_tunda_view',
    ),
    path('yanberkala/', BerkalaListView.as_view(), name='layanan_berkala_view'),
    path('yanberkala/add-layanan/<int:riwayat_id>/', createlayananberkala, name='layanan_berkala_add_view'),
    path('yanberkala/<int:id>/', LayananGajiBerkalaUpdateView.as_view(), name='layanan_berkala_update_view'),
    # path('api/berkala/<int:id>/', LayananGajiBerkalaAPIView.as_view(), name='layanan_berkala_api_view'),
    path('yanberkala/proses/<int:layanan_id>/<str:nip>/', LayananGajiBerkalaAdminView.as_view(), name='layanan_berkala_admin_view'),
    path('yanberkala/proses/add/<int:layanan_id>/<str:nip>/', LayananGajiBerkalaAdminAddView.as_view(), name='layanan_berkala_admin_add_view'),
    path('yanberkala/proses/upload/<int:berkala_id>/<int:layanan_id>/<str:nip>/', LayananGajiBerkalaUpload.as_view(), name='layanan_berkala_admin_upload_view'),
    path('yandiklat-list/', LayananUsulanDiklatView.as_view(), name='layanan_diklat_view'),
    path('yandiklat/', LayananUsulanDiklatListView.as_view(), name='layanan_diklat_list_view'),
    path('yandiklat-staf/', LayananUsulanDiklatStaffView.as_view(), name='layanan_diklat_staf_view'),
    path('yandiklat-usulan/', LayananUsulanDiklatCreateView.as_view(), name='layanan_diklat_usulan_view'),
    path('yandiklat-penugasan/', PenugasanDiklatCreateView.as_view(), name='layanan_diklat_penugasan_view'),
    path('yandiklat-pengalihan/<int:pk>/', PengalihanDiklatCreateView.as_view(), name='layanan_diklat_pengalihan_view'),
    path('yandiklat/<int:pk>/', LayananUsulanDiklatUpdateView.as_view(), name='layanan_diklat_update_view'),
    path('catatan-sdm/<int:pk>/', CatatanSDMUsulanLayananDiklatUpdateView.as_view(), name='catatan_sdm_update_view'),
    path('verifikasi-diklat/<int:pk>/', VerifikasiDiklatView.as_view(), name='verifikasi_diklat_update_view'),
    path('yaninovasi/', LayananUsulanInovasiView.as_view(), name='layanan_inovasi_view'),
    path('yaninovasi/<int:id>/', LayananUsulanInovasiUpdateView.as_view(), name='layanan_inovasi_update_view'),
    path('notifikasi/', NotifikasiView.as_view(), name='notifikasi_view'),
    path('notifikasi/<int:id>/', NotifikasiView.as_view(), name='notifikasi_update_view'),
    path("sip/", LayananSIPListView.as_view(), name="layanan_sip_list"),
    path("sip/tambah/", LayananSIPCreateView.as_view(), name="layanan_sip_create"),
    path("sip/<int:pk>/", LayananSIPDetailView.as_view(), name="layanan_sip_detail"),
    path("sip/<int:pk>/edit/", LayananSIPUpdateView.as_view(), name="layanan_sip_update"),
    path(
        "sip/<int:pk>/upload-persyaratan/",
        LayananSIPUploadPersyaratanView.as_view(),
        name="layanan_sip_upload_persyaratan",
    ),
    path(
        "sip/<int:pk>/upload-rekomendasi/",
        LayananSIPUploadRekomendasiView.as_view(),
        name="layanan_sip_upload_rekomendasi",
    ),
    path('yanpangkat/', LayananNaikPangkatListView.as_view(), name='layanan_pangkat_list'),
    path(
        'api/promosi/<str:service>/<int:employee_id>/dokumen/',
        PromotionSupportingOptionsView.as_view(),
        name='promotion_supporting_options',
    ),
    path('yanpangkat/tambah/', LayananNaikPangkatCreateView.as_view(), name='layanan_pangkat_create'),
    path('yanpangkat/<int:pk>/', LayananNaikPangkatDetailView.as_view(), name='layanan_pangkat_detail'),
    path('yanpangkat/<int:pk>/ubah/', LayananNaikPangkatUpdateView.as_view(), name='layanan_pangkat_update'),
    path('yanpangkat/<int:pk>/proses/', LayananNaikPangkatProcessView.as_view(), name='layanan_pangkat_process'),
    path('yanjabatan/', LayananNaikJabatanListView.as_view(), name='layanan_jabatan_list'),
    path('yanjabatan/tambah/', LayananNaikJabatanCreateView.as_view(), name='layanan_jabatan_create'),
    path('yanjabatan/surat/', SuratUsulanJabatanView.as_view(), name='layanan_jabatan_surat'),
    path('yanjabatan/<int:pk>/', LayananNaikJabatanDetailView.as_view(), name='layanan_jabatan_detail'),
    path('yanjabatan/<int:pk>/ubah/', LayananNaikJabatanUpdateView.as_view(), name='layanan_jabatan_update'),
    path('yanjabatan/<int:pk>/proses/', LayananNaikJabatanProcessView.as_view(), name='layanan_jabatan_process'),
]
