# Generated by Django 5.0 on 2024-07-12 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanMasalah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField(help_text='Tuliskan terjadi error di menu apa? kapan terjadi error, apakah saat baru buka menu atau setelah mengirimkan data? atau permasalahan lainnya silahkan deskripsikan.')),
                ('gambar', models.FileField(upload_to='lapor/')),
                ('status', models.CharField(blank=True, choices=[('Laporan', 'Laporan'), ('Tindaklanjut', 'Tindaklanjut'), ('Selesai', 'Selesai')], max_length=15)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Saran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saran', models.TextField(help_text='Silahkan tuliskan saran anda disini')),
                ('tanggapan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
