# Generated by Django 5.0 on 2024-06-20 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokumen', '0001_initial'),
        ('jenissdm', '0001_initial'),
        ('myaccount', '0001_initial'),
        ('strukturorg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anak',
            name='jk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myaccount.gender'),
        ),
        migrations.AddField(
            model_name='kompetensi',
            name='kompetensi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kompetensi_sdm', to='jenissdm.listkompetensi'),
        ),
        migrations.AddField(
            model_name='kompetensi',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listkompetensifungsional',
            name='kompetensi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.kompetensi'),
        ),
        migrations.AddField(
            model_name='orangtua',
            name='jk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myaccount.gender'),
        ),
        migrations.AddField(
            model_name='pasangan',
            name='jk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myaccount.gender'),
        ),
        migrations.AddField(
            model_name='riwayatbekerja',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatbekerja',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatcuti',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatcuti',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatdiklat',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatdiklat',
            name='kompetensi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diklat_kompetensi', to='jenissdm.listkompetensi'),
        ),
        migrations.AddField(
            model_name='riwayatdiklat',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatgajiberkala',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gaji_berkala', to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatgajiberkala',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayathukuman',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayathukuman',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatinovasi',
            name='bidang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.bidanginovasi'),
        ),
        migrations.AddField(
            model_name='riwayatinovasi',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatinovasi',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatjabatanfungsional',
            name='bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.bidang'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanfungsional',
            name='instalasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitinstalasi'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanfungsional',
            name='jabatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokumen.riwayatjabatan'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanfungsional',
            name='jenjang_jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.jenjangjafung'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanfungsional',
            name='kompetensi',
            field=models.ManyToManyField(blank=True, through='dokumen.ListKompetensiFungsional', to='dokumen.kompetensi'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanfungsional',
            name='nama_jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jenissdm.jenissdm'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanfungsional',
            name='sub_bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.subbidang'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanfungsional',
            name='unor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitorganisasi'),
        ),
        migrations.AddField(
            model_name='listkompetensifungsional',
            name='fungsional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabel_tengah_kompetensi_jafung', to='dokumen.riwayatjabatanfungsional'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanpelaksana',
            name='bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.bidang'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanpelaksana',
            name='instalasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitinstalasi'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanpelaksana',
            name='jabatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokumen.riwayatjabatan'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanpelaksana',
            name='nama_jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jenissdm.jenissdm'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanpelaksana',
            name='sub_bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.subbidang'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanpelaksana',
            name='unor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitorganisasi'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanstruktural',
            name='bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.bidang'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanstruktural',
            name='jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dokumen.riwayatjabatan'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanstruktural',
            name='jenjang_jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.jenjangstruktural'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanstruktural',
            name='sub_bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.subbidang'),
        ),
        migrations.AddField(
            model_name='riwayatjabatanstruktural',
            name='unor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitorganisasi'),
        ),
        migrations.AddField(
            model_name='riwayatkeluarga',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatkeluarga',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pasangan',
            name='keluarga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatkeluarga'),
        ),
        migrations.AddField(
            model_name='orangtua',
            name='keluarga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatkeluarga'),
        ),
        migrations.AddField(
            model_name='anak',
            name='keluarga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatkeluarga'),
        ),
        migrations.AddField(
            model_name='riwayatkinerja',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatkinerja',
            name='kuadran_kinerja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.predikatkinerja', verbose_name='Predikat Kinerja'),
        ),
        migrations.AddField(
            model_name='riwayatkinerja',
            name='nama_penilai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nama_penilai', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatkinerja',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nama_pengguna', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatorganisasi',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatorganisasi',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatpak',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatpak',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatpanggol',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatpanggol',
            name='panggol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.pangkatgolongan'),
        ),
        migrations.AddField(
            model_name='riwayatpanggol',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatgajiberkala',
            name='pangkat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpanggol'),
        ),
        migrations.AddField(
            model_name='riwayatpendidikan',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatpendidikan',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='akreditasiprodi',
            name='pendidikan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokumen.riwayatpendidikan'),
        ),
        migrations.AddField(
            model_name='riwayatpenempatan',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatpenempatan',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatpenempatan',
            name='penempatan_level1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitorganisasi', verbose_name='Instansi'),
        ),
        migrations.AddField(
            model_name='riwayatpenempatan',
            name='penempatan_level2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.bidang', verbose_name='Bidang'),
        ),
        migrations.AddField(
            model_name='riwayatpenempatan',
            name='penempatan_level3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.subbidang', verbose_name='Seksi/Subbagian'),
        ),
        migrations.AddField(
            model_name='riwayatpenempatan',
            name='penempatan_level4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strukturorg.unitinstalasi', verbose_name='Unit/Instalasi'),
        ),
        migrations.AddField(
            model_name='riwayatgajiberkala',
            name='tempat_kerja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpenempatan'),
        ),
        migrations.AddField(
            model_name='riwayatpengangkatan',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatpengangkatan',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatpenghargaan',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatpenghargaan',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatprofesi',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatprofesi',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riwayatprofesi',
            name='profesi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jenissdm.jenissdm'),
        ),
        migrations.AddField(
            model_name='riwayatsipprofesi',
            name='riwayat_profesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokumen.riwayatprofesi'),
        ),
        migrations.AddField(
            model_name='riwayatskp',
            name='dokumen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatskp',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ujikompetensi',
            name='kompetensi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ujikom_kompetensi', to='jenissdm.listkompetensi'),
        ),
        migrations.AddField(
            model_name='ujikompetensi',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
