# Generated by Django 5.0 on 2024-07-02 14:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0002_initial'),
        ('jenissdm', '0001_initial'),
        ('strukturorg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riwayatjabatanfungsional',
            name='kompetensi',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanfungsional',
            name='bidang',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanfungsional',
            name='instalasi',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanfungsional',
            name='jabatan',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanfungsional',
            name='jenjang_jabatan',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanfungsional',
            name='nama_jabatan',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanfungsional',
            name='sub_bidang',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanfungsional',
            name='unor',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanpelaksana',
            name='bidang',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanpelaksana',
            name='instalasi',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanpelaksana',
            name='jabatan',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanpelaksana',
            name='nama_jabatan',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanpelaksana',
            name='sub_bidang',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanpelaksana',
            name='unor',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanstruktural',
            name='bidang',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanstruktural',
            name='jabatan',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanstruktural',
            name='jenjang_jabatan',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanstruktural',
            name='sub_bidang',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatanstruktural',
            name='unor',
        ),
        migrations.RemoveField(
            model_name='riwayatjabatan',
            name='dokumen',
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.bidang'),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='detail_nama_jabatan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='jabatan/sk_fungsional/', verbose_name='SK'),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='file_pemberhentian',
            field=models.FileField(blank=True, null=True, upload_to='jabatan/sk_fungs_pemberhentian/', verbose_name='SK Pemberhentian/Pembebasan'),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='instalasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitinstalasi'),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='jenjang_jabatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.jenjangjafung'),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='jns_jabatan',
            field=models.CharField(choices=[('Struktural', 'Struktural'), ('Fungsional', 'Fungsional'), ('Pelaksana', 'Pelaksana')], default='Jabatan Fungisonal', max_length=50, verbose_name='Jenis Jabatan'),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='kompetensi',
            field=models.ManyToManyField(blank=True, to='dokumen.kompetensi'),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='nama_jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jenissdm.jenissdm'),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='no_sk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='no_srt_pemberhentian',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='sub_bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.subbidang'),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='tgl_sk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='tgl_srt_pemberhentian',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='tmt_jabatan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='tmt_pelantikan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='unor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitorganisasi'),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='riwayatjabatan',
            name='pegawai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ListKompetensiFungsional',
        ),
        migrations.DeleteModel(
            name='RiwayatJabatanFungsional',
        ),
        migrations.DeleteModel(
            name='RiwayatJabatanPelaksana',
        ),
        migrations.DeleteModel(
            name='RiwayatJabatanStruktural',
        ),
    ]
