# Generated by Django 5.0 on 2024-07-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0003_remove_riwayatjabatanfungsional_kompetensi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatpendidikan',
            name='no_ijazah',
            field=models.CharField(max_length=100),
        ),
    ]
