# Generated by Django 5.0 on 2024-07-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0004_alter_riwayatpendidikan_no_ijazah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatpendidikan',
            name='level_pend',
            field=models.CharField(choices=[('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('DI', 'DI'), ('DII', 'DII'), ('DIII', 'DIII'), ('DIV', 'DIV'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=25),
        ),
    ]
