# Generated by Django 5.0 on 2024-07-09 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0005_alter_riwayatpendidikan_level_pend'),
    ]

    operations = [
        migrations.AddField(
            model_name='kompetensi',
            name='dokumen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='dokumen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm'),
        ),
        migrations.AlterField(
            model_name='jenjangstruktural',
            name='jenjang',
            field=models.CharField(blank=True, choices=[('Pengawas', 'Pengawas'), ('Administrator', 'Administrator'), ('JPT Pratama', 'JPT Pratama'), ('JPT Madya', 'JPT Madya')], max_length=30),
        ),
        migrations.AlterField(
            model_name='kompetensi',
            name='file_sert',
            field=models.FileField(blank=True, upload_to='jabatan/kompetensi/', verbose_name='File Sertifikat'),
        ),
        migrations.AlterField(
            model_name='riwayatpanggol',
            name='no_pertek_bkn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
