# Generated by Django 5.0 on 2024-07-21 20:12

import dokumen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0006_kompetensi_dokumen_riwayatjabatan_dokumen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatcuti',
            name='file_pendukung',
            field=models.FileField(blank=True, help_text='Dapat berupa surat ket. penyerahan tugas', upload_to='cuti/pendukung/', validators=[dokumen.models.validate_file_size], verbose_name='Dokumen Pendukung'),
        ),
        migrations.AddField(
            model_name='riwayatcuti',
            name='file_pengajuan',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='cuti/pengajuan/', validators=[dokumen.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='akreditasiprodi',
            name='file_akreditasi',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='pendidikan/akreditasi/', validators=[dokumen.models.validate_file_size], verbose_name='Sert. Akreditasi'),
        ),
        migrations.AlterField(
            model_name='kompetensi',
            name='file_sert',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='jabatan/kompetensi/', validators=[dokumen.models.validate_file_size], verbose_name='File Sertifikat'),
        ),
        migrations.AlterField(
            model_name='pasangan',
            name='file_akte_nikah',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', null=True, upload_to='keluarga/akte/', validators=[dokumen.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='riwayatbekerja',
            name='file',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='bekerja/', validators=[dokumen.models.validate_file_size], verbose_name='SK'),
        ),
        migrations.AlterField(
            model_name='riwayatcuti',
            name='file',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='cuti/surat/', validators=[dokumen.models.validate_file_size], verbose_name='Surat Cuti'),
        ),
        migrations.AlterField(
            model_name='riwayatdiklat',
            name='file',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', null=True, upload_to='diklat/sertifikat/', validators=[dokumen.models.validate_file_size], verbose_name='Sertifikat'),
        ),
        migrations.AlterField(
            model_name='riwayatdiklat',
            name='file_laporan',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', null=True, upload_to='diklat/laporan/', validators=[dokumen.models.validate_file_size], verbose_name='Laporan Pelatihan'),
        ),
        migrations.AlterField(
            model_name='riwayatgajiberkala',
            name='file',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='berkala/', validators=[dokumen.models.validate_file_size], verbose_name='SK'),
        ),
        migrations.AlterField(
            model_name='riwayathukuman',
            name='file',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='hukuman/', validators=[dokumen.models.validate_file_size], verbose_name='SK'),
        ),
        migrations.AlterField(
            model_name='riwayatinovasi',
            name='file_sk',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='inovasi/sk/', validators=[dokumen.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='riwayatinovasi',
            name='makalah',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='inovasi/makalah/', validators=[dokumen.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='riwayatjabatan',
            name='file',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', null=True, upload_to='jabatan/sk_fungsional/', validators=[dokumen.models.validate_file_size], verbose_name='SK'),
        ),
        migrations.AlterField(
            model_name='riwayatjabatan',
            name='file_pemberhentian',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', null=True, upload_to='jabatan/sk_fungs_pemberhentian/', validators=[dokumen.models.validate_file_size], verbose_name='SK Pemberhentian/Pembebasan'),
        ),
        migrations.AlterField(
            model_name='riwayatkeluarga',
            name='file',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='keluarga/kk/', validators=[dokumen.models.validate_file_size], verbose_name='KK'),
        ),
        migrations.AlterField(
            model_name='riwayatkinerja',
            name='file',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='kinerja/', validators=[dokumen.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='riwayatorganisasi',
            name='file',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='organisasi/', validators=[dokumen.models.validate_file_size], verbose_name='Sertifikat'),
        ),
        migrations.AlterField(
            model_name='riwayatpak',
            name='file',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='pak/', validators=[dokumen.models.validate_file_size], verbose_name='File PAK'),
        ),
        migrations.AlterField(
            model_name='riwayatpanggol',
            name='file',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='panggol/', validators=[dokumen.models.validate_file_size], verbose_name='SK'),
        ),
        migrations.AlterField(
            model_name='riwayatpendidikan',
            name='file_ijazah',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='pendidikan/ijazah/', validators=[dokumen.models.validate_file_size], verbose_name='Ijazah'),
        ),
        migrations.AlterField(
            model_name='riwayatpendidikan',
            name='file_srt_penyetaraan',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='pendidikan/penyetaraan/', validators=[dokumen.models.validate_file_size], verbose_name='File Penyetaraan'),
        ),
        migrations.AlterField(
            model_name='riwayatpendidikan',
            name='file_transkrip',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='pendidikan/transkrip/', validators=[dokumen.models.validate_file_size], verbose_name='Transkrip'),
        ),
        migrations.AlterField(
            model_name='riwayatpenempatan',
            name='file',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='penempatan/', validators=[dokumen.models.validate_file_size], verbose_name='SK Penempatan'),
        ),
        migrations.AlterField(
            model_name='riwayatpengangkatan',
            name='file_karpeg',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='pengangkatan/karpeg/', validators=[dokumen.models.validate_file_size], verbose_name='Salinan Karpeg'),
        ),
        migrations.AlterField(
            model_name='riwayatpengangkatan',
            name='file_latsar',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='pengangkatan/latsar/', validators=[dokumen.models.validate_file_size], verbose_name='Sertifikat Latsar'),
        ),
        migrations.AlterField(
            model_name='riwayatpengangkatan',
            name='file_sk',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='pengangkatan/sk/', validators=[dokumen.models.validate_file_size], verbose_name='SK'),
        ),
        migrations.AlterField(
            model_name='riwayatpengangkatan',
            name='file_spmt',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='pengangkatan/spmt/', validators=[dokumen.models.validate_file_size], verbose_name='SPMT'),
        ),
        migrations.AlterField(
            model_name='riwayatpenghargaan',
            name='file',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='penghargaan/', validators=[dokumen.models.validate_file_size], verbose_name='SK'),
        ),
        migrations.AlterField(
            model_name='riwayatprofesi',
            name='file_str',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='profesi/str/', validators=[dokumen.models.validate_file_size], verbose_name='STR'),
        ),
        migrations.AlterField(
            model_name='riwayatsipprofesi',
            name='file_sip',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='profesi/sip/', validators=[dokumen.models.validate_file_size], verbose_name='File SIP'),
        ),
        migrations.AlterField(
            model_name='riwayatskp',
            name='file',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='skp/', validators=[dokumen.models.validate_file_size], verbose_name='SKP'),
        ),
        migrations.AlterField(
            model_name='ujikompetensi',
            name='file_sert',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='jabatan/uji_komp/', validators=[dokumen.models.validate_file_size], verbose_name='File Sertifikat'),
        ),
    ]
