# Generated by Django 5.0 on 2024-07-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0007_riwayatcuti_file_pendukung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatdiklat',
            name='skp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
