# Generated by Django 5.0 on 2024-08-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0008_alter_riwayatdiklat_skp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pangkatgolongan',
            name='golongan',
            field=models.CharField(max_length=5),
        ),
    ]
