# Generated by Django 5.0 on 2024-08-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0009_alter_pangkatgolongan_golongan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatdiklat',
            name='jenis_diklat',
            field=models.CharField(help_text='Contoh: Workshop/Seminar/Pelatihan/Simposium/ dll', max_length=100),
        ),
        migrations.AlterField(
            model_name='riwayatdiklat',
            name='periode_berlaku_sertifikat',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='riwayatdiklat',
            name='skp',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='riwayatprofesi',
            name='tgl_str',
            field=models.DateField(blank=True, null=True, verbose_name='tanggal STR'),
        ),
    ]
