# Generated by Django 5.0 on 2024-09-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0010_alter_riwayatdiklat_jenis_diklat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatpendidikan',
            name='level_pend',
            field=models.CharField(choices=[('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('DI', 'DI'), ('DII', 'DII'), ('DIII', 'DIII'), ('DIV', 'DIV'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('Spesialis', 'Spesialis'), ('Subspesialis', 'Subspesialis')], max_length=25),
        ),
    ]
