# Generated by Django 5.0 on 2024-09-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0011_alter_riwayatpendidikan_level_pend'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumensdm',
            name='view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='riwayatpendidikan',
            name='level_pend',
            field=models.CharField(choices=[('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('DI', 'DI'), ('DII', 'DII'), ('DIII', 'DIII'), ('DIV', 'DIV'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('Profesi', 'Profesi'), ('Spesialis', 'Spesialis'), ('Subspesialis', 'Subspesialis')], max_length=25),
        ),
    ]
