# Generated by Django 5.0 on 2024-09-29 19:50

import django.db.models.deletion
import dokumen.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0012_dokumensdm_view_alter_riwayatpendidikan_level_pend'),
        ('strukturorg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anak',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dokumensdm',
            name='url_param',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kompetensi',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pasangan',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatbekerja',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatcuti',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatdiklat',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatgajiberkala',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayathukuman',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatinovasi',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatjabatan',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatkeluarga',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatkinerja',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatorganisasi',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatpak',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatpanggol',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatpendidikan',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatpenempatan',
            name='bidang_sebelumnya',
            field=models.CharField(blank=True, help_text='Biarkan kosong jika tidak ada', max_length=200, verbose_name='Bidang atau yang setara'),
        ),
        migrations.AddField(
            model_name='riwayatpenempatan',
            name='instansi_sebelumnya',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instansi'),
        ),
        migrations.AddField(
            model_name='riwayatpenempatan',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatpenempatan',
            name='seksi_sebelumnya',
            field=models.CharField(blank=True, help_text='Biarkan kosong jika tidak ada', max_length=200, verbose_name='Seksi atau yang setara'),
        ),
        migrations.AddField(
            model_name='riwayatpenempatan',
            name='unit_sebelumnya',
            field=models.CharField(blank=True, help_text='Biarkan kosong jika tidak ada', max_length=200, verbose_name='Unit atau yang setara'),
        ),
        migrations.AddField(
            model_name='riwayatpengangkatan',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatpenghargaan',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatprofesi',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatsipprofesi',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riwayatskp',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ujikompetensi',
            name='no_urut_dokumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='riwayatjabatan',
            name='jns_jabatan',
            field=models.CharField(choices=[('Struktural', 'Struktural'), ('Fungsional', 'Fungsional'), ('Pelaksana', 'Pelaksana')], default='Fungisonal', max_length=50, verbose_name='Jenis Jabatan'),
        ),
        migrations.AlterField(
            model_name='riwayatpenempatan',
            name='penempatan_level2',
            field=models.ForeignKey(blank=True, help_text='Biar kosong jika tidak ada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.bidang', verbose_name='Bidang'),
        ),
        migrations.AlterField(
            model_name='riwayatpenempatan',
            name='penempatan_level3',
            field=models.ForeignKey(blank=True, help_text='Biarkan kosong jika tidak ada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.subbidang', verbose_name='Seksi/Subbagian'),
        ),
        migrations.AlterField(
            model_name='riwayatpenempatan',
            name='penempatan_level4',
            field=models.ForeignKey(blank=True, help_text='Biarkan kosong jika tidak ada', null=True, on_delete=django.db.models.deletion.CASCADE, to='strukturorg.unitinstalasi', verbose_name='Unit/Instalasi'),
        ),
        migrations.CreateModel(
            name='RiwayatPenugasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_urut_dokumen', models.IntegerField(default=0)),
                ('nama_keg', models.CharField(max_length=250)),
                ('tempat_keg', models.CharField(blank=True, max_length=200)),
                ('peran', models.CharField(blank=True, choices=[('Panitia', 'Panitia'), ('Narasumber', 'Narasumber'), ('Peserta', 'Peserta'), ('Moderator', 'Moderator'), ('MC', 'MC')], max_length=50)),
                ('lama_keg', models.SmallIntegerField(blank=True, null=True)),
                ('tgl_mulai', models.DateField(blank=True)),
                ('tgl_selesai', models.DateField(blank=True)),
                ('anggaran', models.BooleanField(default=False)),
                ('sumber_angg', models.CharField(blank=True, choices=[('RS Mandalika', 'RS Mandalika'), ('Vendor', 'Vendor'), ('Mandiri', 'Mandiri')], max_length=50)),
                ('file_spt', models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='spt/', validators=[dokumen.models.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dokumen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.dokumensdm')),
                ('jabatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatjabatan')),
                ('panggol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dokumen.riwayatpanggol')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
