# Generated by Django 5.0 on 2025-02-28 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0013_anak_no_urut_dokumen_dokumensdm_url_param_and_more'),
        ('layanan', '0010_remove_layananusulandiklat_diklat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatdiklat',
            name='is_usulan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riwayatdiklat',
            name='usulan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.layananusulandiklat'),
        ),
        migrations.AlterField(
            model_name='kompetensi',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pegawai_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='riwayatdiklat',
            name='pegawai',
        ),
        migrations.AddField(
            model_name='riwayatdiklat',
            name='pegawai',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
