# Generated by Django 5.0 on 2025-06-25 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0014_riwayatdiklat_is_usulan_riwayatdiklat_usulan_and_more'),
        ('strukturorg', '0002_standarinstalasi_kompetensi_wajib_parsial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='riwayatpenempatan',
            index=models.Index(fields=['pegawai', 'status'], name='dokumen_riw_pegawai_01f0b7_idx'),
        ),
    ]
