# Generated by Django 5.0 on 2025-07-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0015_riwayatpenempatan_dokumen_riw_pegawai_01f0b7_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riwayatcuti',
            name='tahun_cuti',
        ),
        migrations.AlterField(
            model_name='riwayatcuti',
            name='status_cuti',
            field=models.CharField(choices=[('Tunda', 'Tunda'), ('Proses', 'Proses'), ('Selesai', 'Selesai')], default='Proses', max_length=10),
        ),
    ]
