# Generated by Django 5.0 on 2025-07-31 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0016_remove_riwayatcuti_tahun_cuti_and_more'),
        ('layanan', '0014_remove_layanancuti_cuti'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatcuti',
            name='usulan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layanan.layanancuti'),
        ),
    ]
