# Generated by Django 5.0 on 2025-11-28 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0017_riwayatcuti_usulan'),
        ('strukturorg', '0002_standarinstalasi_kompetensi_wajib_parsial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riwayatpenempatan',
            options={'verbose_name': 'Riwayat Penempatan', 'verbose_name_plural': 'Riwayat Penempatan'},
        ),
        migrations.AddField(
            model_name='riwayatgajiberkala',
            name='has_layanan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riwayatgajiberkala',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='riwayatpenempatan',
            name='bidang_sebelumnya',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bidang atau yang setara'),
        ),
        migrations.AlterField(
            model_name='riwayatpenempatan',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_penempatan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riwayatpenempatan',
            name='penempatan_level1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitorganisasi', verbose_name='Instansi (Level 1)'),
        ),
        migrations.AlterField(
            model_name='riwayatpenempatan',
            name='penempatan_level2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.bidang', verbose_name='Bidang (Level 2)'),
        ),
        migrations.AlterField(
            model_name='riwayatpenempatan',
            name='penempatan_level3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.subbidang', verbose_name='Seksi/Subbagian (Level 3)'),
        ),
        migrations.AlterField(
            model_name='riwayatpenempatan',
            name='penempatan_level4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strukturorg.unitinstalasi', verbose_name='Unit/Instalasi (Level 4)'),
        ),
        migrations.AlterField(
            model_name='riwayatpenempatan',
            name='seksi_sebelumnya',
            field=models.CharField(blank=True, max_length=200, verbose_name='Seksi atau yang setara'),
        ),
        migrations.AlterField(
            model_name='riwayatpenempatan',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status Penempatan Aktif'),
        ),
        migrations.AlterField(
            model_name='riwayatpenempatan',
            name='unit_sebelumnya',
            field=models.CharField(blank=True, max_length=200, verbose_name='Unit atau yang setara'),
        ),
    ]
