# Generated by Django 5.0 on 2025-12-04 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0018_alter_riwayatpenempatan_options_and_more'),
        ('layanan', '0014_remove_layanancuti_cuti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatcuti',
            name='usulan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuti_usulan', to='layanan.layanancuti'),
        ),
    ]
