# Generated by Django 5.0 on 2025-12-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0019_alter_riwayatcuti_usulan'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatcuti',
            name='tahun_cuti',
            field=models.SmallIntegerField(null=True),
        ),
    ]
