# Generated by Django 5.0 on 2025-12-06 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0020_riwayatcuti_tahun_cuti'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlaimCutiTunda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_hari_diklaim', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuti_klaim', models.ForeignKey(help_text='Cuti tahunan yang memakai hak tunda', on_delete=django.db.models.deletion.CASCADE, related_name='klaim_masuk', to='dokumen.riwayatcuti')),
                ('sumber_tunda', models.ForeignKey(limit_choices_to={'status_cuti': 'Tunda'}, on_delete=django.db.models.deletion.CASCADE, related_name='klaim_keluar', to='dokumen.riwayatcuti')),
            ],
            options={
                'verbose_name': 'Klaim Cuti Tunda',
                'verbose_name_plural': 'Klaim Cuti Tunda',
            },
        ),
    ]
