# Generated by Django 5.0 on 2025-12-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0021_klaimcutitunda'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatcuti',
            name='status_persetujuan',
            field=models.CharField(choices=[('belum', 'Belum diputuskan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='belum', help_text='Status hasil persetujuan atasan terhadap pengajuan cuti ini.', max_length=20),
        ),
    ]
