# Generated by Django 5.0 on 2025-12-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0022_riwayatcuti_status_persetujuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatcuti',
            name='pakai_tunda_saja',
            field=models.BooleanField(default=False),
        ),
    ]
