# Generated by Django 5.0 on 2025-12-20 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0023_riwayatcuti_pakai_tunda_saja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='klaimcutitunda',
            name='admin_override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klaimcutitunda',
            name='admin_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klaim_tunda_override', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='klaimcutitunda',
            name='catatan_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='klaimcutitunda',
            name='is_admin_override',
            field=models.BooleanField(default=False),
        ),
    ]
