# Generated by Django 5.0 on 2025-12-30 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0024_klaimcutitunda_admin_override_at_and_more'),
        ('layanan', '0018_verifikasicuti_keputusan1_verifikasicuti_keputusan2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatcuti',
            name='usulan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuti_usulan', to='layanan.layanancuti'),
        ),
    ]
