# Generated by Django 5.0 on 2026-06-05 16:47

import dokumen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0025_alter_riwayatcuti_usulan'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatpendidikan',
            name='file_verifikasi',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='pendidikan/verifikasi/', validators=[dokumen.models.validate_file_size], verbose_name='File Hasil Verifikasi'),
        ),
        migrations.AddField(
            model_name='riwayatpendidikan',
            name='is_verifikasi',
            field=models.BooleanField(default=False),
        ),
    ]
