# Generated by Django 5.0 on 2026-07-15 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0026_riwayatpendidikan_file_verifikasi_and_more'),
        ('layanan', '0026_rename_layananpengakuangelar_layananpencantumangelar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatjabatan',
            name='usulan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.layanannaikjabatan'),
        ),
        migrations.AddField(
            model_name='riwayatpanggol',
            name='usulan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layanan.layanannaikpangkat'),
        ),
    ]
