# Generated by Django 5.0 on 2026-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0032_kewajibandokumen_wajib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatcuti',
            name='status_cuti',
            field=models.CharField(choices=[('Tunda', 'Tunda'), ('Proses', 'Proses'), ('Selesai', 'Selesai'), ('Ditolak', 'Ditolak')], default='Proses', max_length=10),
        ),
    ]
