ADMIN_DASHBOARD = "Admin Dashboard"
ADMIN_DOKUMEN = "Admin Dokumen SDM"
ADMIN_LAYANAN_CUTI = "Admin Layanan Cuti"
ADMIN_LAYANAN_BERKALA = "Admin Layanan Berkala"
ADMIN_LAYANAN_PANGKAT = "Admin Layanan Pangkat"
ADMIN_LAYANAN_JABATAN = "Admin Layanan Jabatan"
ADMIN_LAYANAN_DIKLAT = "Admin Layanan Diklat"
ADMIN_LAYANAN_INOVASI = "Admin Layanan Inovasi"
ADMIN_LAYANAN_SIP = "Admin Layanan SIP"
ADMIN_DISIPLIN = "Admin Disiplin SDM"
ADMIN_INFORMASI = "Admin Informasi"
ADMIN_LAPORAN = "Admin Laporan"
ADMIN_AKUN = "Admin Akun"
ADMIN_SSO = "Admin SSO"


ADMIN_GROUPS = (
    ADMIN_DASHBOARD,
    ADMIN_DOKUMEN,
    ADMIN_LAYANAN_CUTI,
    ADMIN_LAYANAN_BERKALA,
    ADMIN_LAYANAN_PANGKAT,
    ADMIN_LAYANAN_JABATAN,
    ADMIN_LAYANAN_DIKLAT,
    ADMIN_LAYANAN_INOVASI,
    ADMIN_LAYANAN_SIP,
    ADMIN_DISIPLIN,
    ADMIN_INFORMASI,
    ADMIN_LAPORAN,
    ADMIN_AKUN,
    ADMIN_SSO,
)
