from django.urls import path

from .views import (
    logout_view, 
    SimaduLoginView, 
    ChangePassword, 
    ChangePasswordDone, 
    ProfilListView, 
    ProfilDetailView, 
    ProfilUpdateView, 
    ProfilCreateView,
    UlangTahunSebulanTerakhirListView,
    PegawaiAutocompleteView,
    sso_portal,
    sso_go,
    access_denied_view,
    cek_jaringan_lokal,
    app_gateway,
    back_view,
    AccountManagementListView,
    AccountResetPasswordView,
    AccountToggleActiveView,
    AccountToggleStaffView,
    AccountToggleDocumentAdminView,
    AccountUpdateAdminRolesView,
    EmployeeRegistrationSuccessView,
    EmployeeRegistrationView,
    AccountRegistrationApproveView,
    AccountRegistrationRejectView,
    AccountRegistrationReviewListView,
    StructuralOfficerDeactivateView,
    StructuralOfficerManagementView,
)
from .views_api import api_me, PegawaiAPIView, DokterSpesialisAPIView, DetailMeAPIView
from .telegram_views import (
    TelegramPasswordResetCompleteView,
    TelegramPasswordResetConfirmView,
    TelegramResetHelpView,
    TelegramWebhookView,
)


urlpatterns=[
    path('login/', SimaduLoginView.as_view(), name='login_view'),
    path('registrasi/', EmployeeRegistrationView.as_view(), name='account_registration'),
    path('registrasi/berhasil/', EmployeeRegistrationSuccessView.as_view(), name='account_registration_success'),
    path('logout/', logout_view, name='logout_view'),
    path('to-sso/', back_view, name='back_view'),
    path('ganti-password/', ChangePassword.as_view(), name='ganti_password_view'),
    path('ganti-password/done/', ChangePasswordDone.as_view(), name='ganti_password_done_view'),
    path('reset-password/', TelegramResetHelpView.as_view(), name='telegram_reset_help'),
    path('telegram/webhook/', TelegramWebhookView.as_view(), name='telegram_webhook'),
    path(
        'telegram/reset/<uidb64>/<token>/',
        TelegramPasswordResetConfirmView.as_view(),
        name='telegram_password_reset_confirm',
    ),
    path(
        'telegram/reset/selesai/',
        TelegramPasswordResetCompleteView.as_view(),
        name='telegram_password_reset_complete',
    ),
    path('pengelolaan-akun/', AccountManagementListView.as_view(), name='account_management_list'),
    path('pengelolaan-akun/registrasi/', AccountRegistrationReviewListView.as_view(), name='account_registration_review_list'),
    path('pengelolaan-akun/registrasi/<int:pk>/setujui/', AccountRegistrationApproveView.as_view(), name='account_registration_approve'),
    path('pengelolaan-akun/registrasi/<int:pk>/tolak/', AccountRegistrationRejectView.as_view(), name='account_registration_reject'),
    path('pengelolaan-akun/<int:pk>/reset-password/', AccountResetPasswordView.as_view(), name='account_reset_password'),
    path('pengelolaan-akun/<int:pk>/toggle-active/', AccountToggleActiveView.as_view(), name='account_toggle_active'),
    path('pengelolaan-akun/<int:pk>/toggle-staff/', AccountToggleStaffView.as_view(), name='account_toggle_staff'),
    path('pengelolaan-akun/<int:pk>/toggle-admin-dokumen/', AccountToggleDocumentAdminView.as_view(), name='account_toggle_document_admin'),
    path('pengelolaan-akun/<int:pk>/hak-akses/', AccountUpdateAdminRolesView.as_view(), name='account_update_admin_roles'),
    path('pengelolaan-akun/pejabat-struktural/', StructuralOfficerManagementView.as_view(), name='structural_officer_management'),
    path('pengelolaan-akun/pejabat-struktural/<int:pk>/nonaktifkan/', StructuralOfficerDeactivateView.as_view(), name='structural_officer_deactivate'),
    path('profil/', ProfilListView.as_view(), name='profil_view'),
    path('profil/add/', ProfilCreateView.as_view(), name='profil_create_view'),
    path('profil/detail/<int:pk>/', ProfilDetailView.as_view(), name='profil_detail_view'),
    path('profil/<int:pk>/update/', ProfilUpdateView.as_view(), name='profil_update_view'),
    path('pegawai-ultah/', UlangTahunSebulanTerakhirListView.as_view(), name='pegawai_ultah_sebulan'),
    path('ajax-pegawai-autocomplete/', PegawaiAutocompleteView.as_view(), name='ajax_pegawai_autocomplete'),
    
    path('api/me/', DetailMeAPIView.as_view(), name='api_me'),
    path('api/pegawai/', PegawaiAPIView.as_view(), name='pegawai_api_view'),
    path('api/dokter-spesialis/', DokterSpesialisAPIView.as_view(), name='dokter_spesialis_api_view'),
    path('api/pegawai/me/', DetailMeAPIView.as_view(), name='detail_me_api_view'),
    path('sso/', sso_portal, name='sso_portal'),
    path('sso/<str:client_key>/', sso_go, name='sso_go'),
    path('access-denied/', access_denied_view, name='local_only_blocked'),
    path('cek-jaringan-lokal/', cek_jaringan_lokal, name='cek_jaringan_lokal'),
    path('app-gateway/', app_gateway, name='app_gateway'),
]
