from .models import (
    Kompetensi,
    RiwayatBekerja,
    RiwayatCuti,
    RiwayatDiklat,
    RiwayatGajiBerkala,
    RiwayatHukuman,
    RiwayatInovasi,
    RiwayatJabatan,
    RiwayatKeluarga,
    RiwayatKinerja,
    RiwayatOrganisasi,
    RiwayatPAK,
    RiwayatPanggol,
    RiwayatPendidikan,
    RiwayatPenempatan,
    RiwayatPengangkatan,
    RiwayatPenghargaan,
    RiwayatPenugasan,
    RiwayatProfesi,
    UjiKompetensi,
)


DOCUMENT_TYPES = {
    'pendidikan': ('Riwayat Pendidikan', RiwayatPendidikan),
    'panggol': ('Riwayat Pangkat dan Golongan', RiwayatPanggol),
    'jabatan': ('Riwayat Jabatan', RiwayatJabatan),
    'pengangkatan': ('Riwayat Pengangkatan', RiwayatPengangkatan),
    'penempatan': ('Riwayat Penempatan', RiwayatPenempatan),
    'berkala': ('Riwayat Gaji Berkala', RiwayatGajiBerkala),
    'kinerja': ('Riwayat Kinerja', RiwayatKinerja),
    'pak': ('Riwayat PAK', RiwayatPAK),
    'ujikomp': ('Riwayat Uji Kompetensi', UjiKompetensi),
    'penghargaan': ('Riwayat Penghargaan', RiwayatPenghargaan),
    'hukuman': ('Riwayat Hukuman', RiwayatHukuman),
    'cuti': ('Riwayat Cuti', RiwayatCuti),
    'diklat': ('Riwayat Diklat', RiwayatDiklat),
    'kompetensi': ('Riwayat Kompetensi', Kompetensi),
    'organisasi': ('Riwayat Organisasi', RiwayatOrganisasi),
    'profesi': ('Riwayat Profesi', RiwayatProfesi),
    'bekerja': ('Riwayat Pengalaman Kerja', RiwayatBekerja),
    'keluarga': ('Riwayat Keluarga', RiwayatKeluarga),
    'inovasi': ('Riwayat Inovasi', RiwayatInovasi),
    'penugasan': ('Riwayat Penugasan', RiwayatPenugasan),
}
