from django.urls import path

from .views import (
    RiwayatHomeView,
    UrutkanRiwayatPendidikanView,
    RiwayatPendidikanView,
    RiwayatPendidikanUpdateView,
    RiwayatPendidikanDeleteView,
    RiwayatPanggolView,
    RiwayatPanggolUpdateView,
    UrutkanRiwayatPanggolView,
    RiwayatPanggolDeleteView,
    RiwayatPengangkatanView,
    RiwayatPengangkatanUpdateView,
    UrutkanRiwayatPengangkatanView,
    RiwayatPengangkatanDeleteView,
    RiwayatJabatanView,
    RiwayatJabatanUpdateView,
    UrutkanRiwayatJabatanView,
    RiwayatJabatanDeleteView,
    RiwayatPenempatanView,
    RiwayatPenempatanInstansiBeforeCreateView,
    RiwayatPenempatanInstansiBeforUpdateView,
    # RiwayatPenempatanUpdateView,
    UrutkanRiwayatPenempatanView,
    RiwayatPenempatanDeleteView,
    RiwayatGajiBerkalaView,
    RiwayatGajiBerkalaUpdateView,
    UrutkanRiwayatGajiBerkalaView,
    RiwayatGajiBerkalaDeleteView,
    RiwayatKinerjaView,
    RiwayatKinerjaUpdateView,
    UrutkanRiwayatKinerjaView,
    RiwayatKinerjaDeleteView,
    RiwayatPenghargaanView,
    RiwayatPenghargaanUpdateView,
    UrutkanRiwayatPenghargaanView,
    RiwayatPenghargaanDeleteView,
    RiwayatHukumanView,
    RiwayatHukumanUpdateView,
    UrutkanRiwayatHukumanView,
    RiwayatHukumanDeleteView,
    RiwayatCutiView,
    RiwayatCutiUpdateView,
    UrutkanRiwayatCutiView,
    RiwayatDiklatListView,
    RiwayatDiklatDetailView,
    RiwayatDiklatCreateView,
    RiwayatDiklatView,
    RiwayatDiklatPegawaiView,
    RiwayatDiklatUpdateView,
    UrutkanRiwayatDiklatView,
    RiwayatDiklatDeleteView,
    RiwayatKompetensiView,
    RiwayatKomptensiUpdateView,
    UrutkanRiwayatKompetensiView,
    RiwayatKompetensiDeleteView,
    RiwayatOrganisasiView,
    RiwayatOrganisasiUpdateView,
    UrutkanRiwayatOrganisasiView,
    RiwayatOrganisasiDeleteView,
    RiwayatProfesiView,
    RiwayatSIPProfesiView,
    RiwayatProfesiUpdateView,
    RiwayatSIPProfesiUpdateView,
    UrutkanRiwayatSIPProfesiView,
    RiwayatProfesiDeleteView,
    RiwayatSIPDeleteView,
    RiwayatBekerjaView,
    RiwayatBekerjaUpdateView,
    UrutkanRiwayatBekerjaView,
    RiwayatBekerjaDeleteView,
    RiwayatKeluargaView,
    RiwayatKeluargaUpdateView,
    RiwayatKeluargaDeleteView,
    RiwayatAnggotaKeluargaView,
    RiwayatAnggotaKeluargaUpdateView,
    RiwayatOrangTuaDeleteView,
    RiwayatInovasiView,
    RiwayatInovasiDeleteView,
    UrutkanRiwayatInovasiView,
    RiwayatPenugasanListView,
    RiwayatPenugasanCreateView,
    RiwayatPenugasanUpdateView,
    RiwayatPenugasanDeleteView,
    UrutkanRiwayatPenugasanView,
    GetListRiwayatSDM,
    RiwayatKelengkapan,
    NotFoundPage
)


urlpatterns=[
    path('', RiwayatHomeView.as_view(), name='riwayat_view'),
    path('pendidikan/', RiwayatPendidikanView.as_view(), name='riwayat_pendidikan'),
    path('pendidikan/<int:id>/', RiwayatPendidikanUpdateView.as_view(), name='riwayat_update_pendidikan'),
    path('pendidikan/delete/<int:pk>/', RiwayatPendidikanDeleteView.as_view(), name='riwayat_delete_pendidikan'),
    path('pendidikan/urutkan/<int:pk>/', UrutkanRiwayatPendidikanView.as_view(), name='riwayat_pendidikan_urutkan'),
    path('panggol/', RiwayatPanggolView.as_view(), name='riwayat_panggol'),
    path('panggol/<int:id>/', RiwayatPanggolUpdateView.as_view(), name='riwayat_update_panggol'),
    path('panggol/urutkan/<int:pk>/', UrutkanRiwayatPanggolView.as_view(), name='riwayat_panggol_urutkan'),
    path('panggol/delete/<int:pk>/', RiwayatPanggolDeleteView.as_view(), name='riwayat_delete_panggol'),
    path('pengangkatan/', RiwayatPengangkatanView.as_view(), name='riwayat_pengangkatan'),
    path('pengangkatan/<int:id>/', RiwayatPengangkatanUpdateView.as_view(), name='riwayat_update_pengangkatan'),
    path('pengangkatan/urutkan/<int:pk>/', UrutkanRiwayatPengangkatanView.as_view(), name='riwayat_pengangkatan_urutkan'),
    path('pengangkatan/delete/<int:pk>/', RiwayatPengangkatanDeleteView.as_view(), name='riwayat_delete_pengangkatan'),
    path('jabatan/', RiwayatJabatanView.as_view(), name='riwayat_jabatan'),
    path('jabatan/<int:id>/', RiwayatJabatanUpdateView.as_view(), name='riwayat_update_jabatan'),
    path('jabatan/urutkan/<int:pk>/', UrutkanRiwayatJabatanView.as_view(), name='riwayat_jabatan_urutkan'),
    path('jabatan/delete/<int:pk>/', RiwayatJabatanDeleteView.as_view(), name='riwayat_delete_jabatan'),
    path('penempatan/', RiwayatPenempatanView.as_view(), name='riwayat_penempatan'),
    path('penempatan/<int:id>/', RiwayatPenempatanView.as_view(), name='riwayat_update_penempatan'),
    path('penempatan/urutkan/<int:pk>/', UrutkanRiwayatPenempatanView.as_view(), name='riwayat_penempatan_urutkan'),
    path('penempatan/delete/<int:pk>/', RiwayatPenempatanDeleteView.as_view(), name='riwayat_delete_penempatan'),
    path('penempatan-lainnya/', RiwayatPenempatanInstansiBeforeCreateView.as_view(), name='riwayat_penempatan_lainnya'),
    path('penempatan-lainnya/<int:pk>/', RiwayatPenempatanInstansiBeforUpdateView.as_view(), name='riwayat_update_penempatan_lainnya'),
    path('berkala/', RiwayatGajiBerkalaView.as_view(), name='riwayat_berkala'),
    path('berkala/<int:id>/', RiwayatGajiBerkalaUpdateView.as_view(), name='riwayat_update_berkala'),
    path('berkala/urutkan/<int:pk>/', UrutkanRiwayatGajiBerkalaView.as_view(), name='riwayat_berkala_urutkan'),
    path('berkala/delete/<int:pk>/', RiwayatGajiBerkalaDeleteView.as_view(), name='riwayat_delete_berkala'),
    path('kinerja/', RiwayatKinerjaView.as_view(), name='riwayat_kinerja'),
    path('kinerja/<int:id>/', RiwayatKinerjaUpdateView.as_view(), name='riwayat_update_kinerja'),
    path('kinerja/urutkan/<int:pk>/', UrutkanRiwayatKinerjaView.as_view(), name='riwayat_kinerja_urutkan'),
    path('kinerja/delete/<int:pk>/', RiwayatKinerjaDeleteView.as_view(), name='riwayat_delete_kinerja'),
    path('penghargaan/', RiwayatPenghargaanView.as_view(), name='riwayat_penghargaan'),
    path('penghargaan/<int:id>/', RiwayatPenghargaanUpdateView.as_view(), name='riwayat_update_penghargaan'),
    path('penghargaan/urutkan/<int:pk>/', UrutkanRiwayatPenghargaanView.as_view(), name='riwayat_penghargaan_urutkan'),
    path('penghargaan/delete/<int:pk>/', RiwayatPenghargaanDeleteView.as_view(), name='riwayat_delete_penghargaan'),
    path('hukuman/', RiwayatHukumanView.as_view(), name='riwayat_hukuman'),
    path('hukuman/<int:id>/', RiwayatHukumanUpdateView.as_view(), name='riwayat_update_hukuman'),
    path('hukuman/urutkan/<int:pk>/', UrutkanRiwayatHukumanView.as_view(), name='riwayat_hukuman_urutkan'),
    path('hukuman/delete/<int:pk>/', RiwayatHukumanDeleteView.as_view(), name='riwayat_delete_hukuman'),
    path('cuti/', RiwayatCutiView.as_view(), name='riwayat_cuti'),
    path('cuti/<int:id>/', RiwayatCutiUpdateView.as_view(), name='riwayat_update_cuti'),
    path('cuti/urutkan/<int:pk>/', UrutkanRiwayatCutiView.as_view(), name='riwayat_cuti_urutkan'),
    path('diklat/', RiwayatDiklatListView.as_view(), name='riwayat_diklat'),
    path('diklat/create/', RiwayatDiklatCreateView.as_view(), name='riwayat_diklat_create'),
    path('diklat/<int:pk>/', RiwayatDiklatDetailView.as_view(), name='riwayat_diklat_detail'),
    path('diklat-pegawai/', RiwayatDiklatPegawaiView.as_view(), name='riwayat_diklat_pegawai'),
    path('diklat/<int:id>/', RiwayatDiklatUpdateView.as_view(), name='riwayat_update_diklat'),
    path('diklat/urutkan/<int:pk>/', UrutkanRiwayatDiklatView.as_view(), name='riwayat_diklat_urutkan'),
    path('diklat/delete/<int:pk>/', RiwayatDiklatDeleteView.as_view(), name='riwayat_delete_diklat'),
    path('kompetensi/', RiwayatKompetensiView.as_view(), name='riwayat_kompetensi'),
    path('kompetensi/<int:id>/', RiwayatKomptensiUpdateView.as_view(), name='riwayat_update_kompetensi'),
    path('kompetensi/urutkan/<int:pk>/', UrutkanRiwayatKompetensiView.as_view(), name='riwayat_kompetensi_urutkan'),
    path('kompetensi/delete/<int:pk>/', RiwayatKompetensiDeleteView.as_view(), name='riwayat_delete_kompetensi'),
    path('organisasi/', RiwayatOrganisasiView.as_view(), name='riwayat_organisasi'),
    path('organisasi/<int:id>/', RiwayatOrganisasiUpdateView.as_view(), name='riwayat_update_organisasi'),
    path('organisasi/urutkan/<int:pk>/', UrutkanRiwayatOrganisasiView.as_view(), name='riwayat_organisasi_urutkan'),
    path('organisasi/delete/<int:pk>/', RiwayatOrganisasiDeleteView.as_view(), name='riwayat_delete_organisasi'),
    path('profesi/', RiwayatProfesiView.as_view(), name='riwayat_profesi'),
    path('profesi/<int:id>/', RiwayatProfesiUpdateView.as_view(), name='riwayat_update_profesi'),
    path('profesi/delete/<int:pk>/', RiwayatProfesiDeleteView.as_view(), name='riwayat_delete_profesi'),
    path('sip/<int:id>/', RiwayatSIPProfesiView.as_view(), name='riwayat_sipprofesi'),
    path('sip/update/<int:id_str>/<int:id>/', RiwayatSIPProfesiUpdateView.as_view(), name='riwayat_update_sipprofesi'),
    path('sip/urutkan/<int:pk>/', UrutkanRiwayatSIPProfesiView.as_view(), name='riwayat_sip_urutkan'),
    path('sip/delete/<int:id_str>/<int:pk>/', RiwayatSIPDeleteView.as_view(), name='riwayat_delete_sipprofesi'),
    path('bekerja/', RiwayatBekerjaView.as_view(), name='riwayat_bekerja'),
    path('bekerja/<int:id>/', RiwayatBekerjaUpdateView.as_view(), name='riwayat_update_bekerja'),
    path('bekerja/urutkan/<int:pk>/', UrutkanRiwayatBekerjaView.as_view(), name='riwayat_bekerja_urutkan'),
    path('bekerja/delete/<int:pk>/', RiwayatBekerjaDeleteView.as_view(), name='riwayat_delete_bekerja'),
    path('keluarga/', RiwayatKeluargaView.as_view(), name='riwayat_keluarga'),
    path('keluarga/<int:id>/', RiwayatKeluargaUpdateView.as_view(), name='riwayat_update_keluarga'),
    path('keluarga/delete/<int:pk>/', RiwayatKeluargaDeleteView.as_view(), name='riwayat_delete_keluarga'),
    path('anggota-keluarga/<str:status>/<int:keluarga_id>/', RiwayatAnggotaKeluargaView.as_view(), name='riwayat_anggota_keluarga'),
    path('anggota-keluarga/<str:status>/<int:keluarga_id>/<int:id>/', RiwayatAnggotaKeluargaUpdateView.as_view(), name='riwayat_update_anggota_keluarga'),
    path('orangtua/delete/<int:pk>/', RiwayatOrangTuaDeleteView.as_view(), name='riwayat_delete_orangtua'),
    path('inovasi/', RiwayatInovasiView.as_view(), name='riwayat_inovasi'),
    path('inovasi/delete/<int:pk>/', RiwayatInovasiDeleteView.as_view(), name='riwayat_delete_inovasi'),
    path('inovasi/urutkan/<int:pk>/', UrutkanRiwayatInovasiView.as_view(), name='riwayat_inovasi_urutkan'),
    path('penugasan/', RiwayatPenugasanListView.as_view(), name='riwayat_penugasan'),
    path('penugasan/add/', RiwayatPenugasanCreateView.as_view(), name="riwayat_add_penugasan"),
    path('penugasan/<int:pk>/', RiwayatPenugasanUpdateView.as_view(), name='riwayat_update_penugasan'),
    path('penugasan/delete/<int:pk>/', RiwayatPenugasanDeleteView.as_view(), name='riwayat_delete_penugasan'),
    path('penugasan/urutkan/<int:pk>/', UrutkanRiwayatPenugasanView.as_view(), name='riwayat_penugasan_urutkan'),
    path('listdok/', GetListRiwayatSDM.as_view(), name='get_riwayat_sdm'),
    path('blankpage/<str:bagian>/<str:selected>/', NotFoundPage.as_view(), name='notfound_view'),
    path('cekdata/', RiwayatKelengkapan.as_view(), name='riwayat_kelengkapan_view'),
]