# Generated by Django 5.0 on 2024-06-20 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jenissdm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimpinan', models.CharField(blank=True, max_length=100)),
                ('bidang', models.CharField(max_length=100)),
                ('nama_pimpinan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstansiDaerah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimpinan', models.CharField(blank=True, max_length=100)),
                ('instansi', models.CharField(max_length=100)),
                ('nama_pimpinan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SatuanKerjaInduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimpinan', models.CharField(blank=True, max_length=100)),
                ('satuan_kerja', models.CharField(max_length=100)),
                ('instansi_daerah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strukturorg.instansidaerah')),
                ('nama_pimpinan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubBidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimpinan', models.CharField(blank=True, max_length=100)),
                ('sub_bidang', models.CharField(max_length=100)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strukturorg.bidang')),
                ('nama_pimpinan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitInstalasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimpinan', models.CharField(blank=True, max_length=100)),
                ('instalasi', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, choices=[('kurang', 'kurang'), ('bagus', 'bagus'), ('mantap', 'mantap')], max_length=10)),
                ('nama_pimpinan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sub_bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strukturorg.subbidang')),
            ],
        ),
        migrations.CreateModel(
            name='StandarInstalasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_sdm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jenissdm.jenissdm')),
                ('kompetensi_pendukung', models.ManyToManyField(blank=True, related_name='kompetensi_pendukung_sdm', to='jenissdm.listkompetensi')),
                ('kompetensi_wajib', models.ManyToManyField(blank=True, related_name='kompetensi_wajib_sdm', to='jenissdm.listkompetensi')),
                ('instalasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strukturorg.unitinstalasi')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimpinan', models.CharField(blank=True, max_length=100)),
                ('unor', models.CharField(max_length=100)),
                ('nama_pimpinan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('satker_induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strukturorg.satuankerjainduk')),
            ],
        ),
        migrations.CreateModel(
            name='StandarSDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.SmallIntegerField(null=True)),
                ('status_wajib', models.BooleanField(default=False)),
                ('jenis_sdm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jenissdm.jenissdm')),
                ('unor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strukturorg.unitorganisasi')),
            ],
        ),
        migrations.AddField(
            model_name='bidang',
            name='unor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strukturorg.unitorganisasi'),
        ),
    ]
