# Generated by Django 5.0 on 2025-02-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenissdm', '0002_remove_listkompetensi_sifat'),
        ('strukturorg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarinstalasi',
            name='kompetensi_wajib_parsial',
            field=models.ManyToManyField(blank=True, related_name='kompetensi_wajib_parsial_sdm', to='jenissdm.listkompetensi'),
        ),
        migrations.AddField(
            model_name='unitinstalasi',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
