# Generated by Django 5.0 on 2024-09-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informasi', '0002_informasisdm_kategoriinformasi_kategorivideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasisdm',
            name='judul',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='informasisdm',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='videoyoutube',
            name='judul_video',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='videoyoutube',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
