# Generated by Django 5.0 on 2024-06-20 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disiplinsdm', '0001_initial'),
        ('jenissdm', '0001_initial'),
        ('strukturorg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarkegiatanpegawai',
            name='bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.bidang'),
        ),
        migrations.AddField(
            model_name='daftarkegiatanpegawai',
            name='instalasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitinstalasi'),
        ),
        migrations.AddField(
            model_name='daftarkegiatanpegawai',
            name='jenis_sdm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jenissdm.jenissdm'),
        ),
        migrations.AddField(
            model_name='daftarkegiatanpegawai',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daftarkegiatanpegawai',
            name='sub_bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.subbidang'),
        ),
        migrations.AddField(
            model_name='daftarkegiatanpegawai',
            name='unor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitorganisasi'),
        ),
        migrations.AddField(
            model_name='jadwaldinassdm',
            name='kategori_jadwal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disiplinsdm.detailkategorijadwaldinas'),
        ),
        migrations.AddField(
            model_name='daftarkegiatanpegawai',
            name='kegiatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disiplinsdm.jeniskegiatan'),
        ),
        migrations.AddField(
            model_name='jenissdmperinstalasi',
            name='bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.bidang'),
        ),
        migrations.AddField(
            model_name='jenissdmperinstalasi',
            name='instalasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitinstalasi'),
        ),
        migrations.AddField(
            model_name='jenissdmperinstalasi',
            name='jenis_sdm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jenissdm.jenissdm'),
        ),
        migrations.AddField(
            model_name='jenissdmperinstalasi',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jenissdmperinstalasi',
            name='sub_bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.subbidang'),
        ),
        migrations.AddField(
            model_name='jenissdmperinstalasi',
            name='unor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitorganisasi'),
        ),
        migrations.AddField(
            model_name='jadwaldinassdm',
            name='pegawai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disiplinsdm.jenissdmperinstalasi'),
        ),
        migrations.AddField(
            model_name='detailkategorijadwaldinas',
            name='kategori_dinas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disiplinsdm.kategorijadwaldinas'),
        ),
        migrations.AddField(
            model_name='kehadirankegiatan',
            name='alasan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disiplinsdm.alasantidakhadir'),
        ),
        migrations.AddField(
            model_name='kehadirankegiatan',
            name='pegawai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disiplinsdm.daftarkegiatanpegawai'),
        ),
    ]
