# Generated by Django 5.0 on 2024-07-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailkategorijadwaldinas',
            name='hari',
            field=models.CharField(blank=True, choices=[('Senin s/d kamis', 'Senin s/d kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=50),
        ),
    ]
