# Generated by Django 5.0 on 2025-06-17 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0003_alter_detailkategorijadwaldinas_hari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadirankegiatan',
            name='pegawai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disiplinsdm.daftarkegiatanpegawai'),
        ),
    ]
