# Generated by Django 5.0 on 2025-06-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0004_alter_kehadirankegiatan_pegawai'),
    ]

    operations = [
        migrations.AddField(
            model_name='kehadirankegiatan',
            name='status_ketepatan',
            field=models.CharField(blank=True, choices=[('Tepat Waktu', 'Tepat Waktu'), ('Terlambat', 'Terlambat'), ('Cepat Pulang', 'Cepat Pulang')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kehadirankegiatan',
            name='tanggal',
            field=models.DateTimeField(),
        ),
    ]
