# Generated by Django 5.0 on 2025-06-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0005_kehadirankegiatan_status_ketepatan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HariLibur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(unique=True)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
