# Generated by Django 5.0 on 2025-06-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0006_harilibur'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenissdmperinstalasi',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('diajukan', 'Diajukan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='draft', max_length=20),
        ),
    ]
