# Generated by Django 5.0 on 2025-06-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0007_jenissdmperinstalasi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailkategorijadwaldinas',
            name='durasi_kerja',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailkategorijadwaldinas',
            name='hari',
            field=models.CharField(blank=True, choices=[('Senin s/d kamis', 'Senin s/d kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], max_length=50),
        ),
    ]
