# Generated by Django 5.0 on 2025-06-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0008_detailkategorijadwaldinas_durasi_kerja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailkategorijadwaldinas',
            name='durasi_kerja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
