# Generated by Django 5.0 on 2025-06-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0009_alter_detailkategorijadwaldinas_durasi_kerja'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailkategorijadwaldinas',
            name='akronim',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
