# Generated by Django 5.0 on 2025-07-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0010_detailkategorijadwaldinas_akronim'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwaldinassdm',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
