# Generated by Django 5.0 on 2025-07-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0011_jadwaldinassdm_catatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwaldinassdm',
            name='catatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
