# Generated by Django 5.0 on 2025-07-05 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0012_alter_jadwaldinassdm_catatan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedJadwalDinasSDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('catatan', models.CharField(blank=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kategori_jadwal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disiplinsdm.detailkategorijadwaldinas')),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disiplinsdm.jenissdmperinstalasi')),
            ],
        ),
    ]
