# Generated by Django 5.0 on 2025-07-06 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0013_approvedjadwaldinassdm'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenissdmperinstalasi',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jenissdmperinstalasi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jenissdmperinstalasi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
