# Generated by Django 5.0 on 2025-08-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0014_jenissdmperinstalasi_alasan_penolakan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AturanToleransiKeterlambatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aturan', models.CharField(help_text='Deskripsi singkat aturan, misal: Toleransi Tepat Waktu', max_length=100)),
                ('batas_atas_menit', models.PositiveIntegerField(help_text='Batas atas keterlambatan dalam menit untuk aturan ini.')),
                ('status_yang_dihasilkan', models.CharField(choices=[('Tepat Waktu', 'Tepat Waktu'), ('Terlambat Ringan', 'Terlambat Ringan'), ('Terlambat Sedang', 'Terlambat Sedang'), ('Terlambat Berat', 'Terlambat Berat'), ('Cepat Pulang', 'Cepat Pulang')], help_text='Status yang akan diberikan jika keterlambatan memenuhi aturan ini.', max_length=30)),
                ('urutan', models.PositiveSmallIntegerField(default=0, help_text='Urutan evaluasi aturan, dari yang terkecil (paling ketat) ke terbesar.')),
                ('is_aktif', models.BooleanField(default=True, help_text='Aktifkan atau nonaktifkan aturan ini.')),
            ],
            options={
                'verbose_name': 'Aturan Toleransi Keterlambatan',
                'verbose_name_plural': 'Aturan Toleransi Keterlambatan',
                'ordering': ['urutan'],
            },
        ),
        migrations.AlterField(
            model_name='kehadirankegiatan',
            name='status_ketepatan',
            field=models.CharField(blank=True, choices=[('Tepat Waktu', 'Tepat Waktu'), ('Terlambat Ringan', 'Terlambat Ringan'), ('Terlambat Sedang', 'Terlambat Sedang'), ('Terlambat Berat', 'Terlambat Berat'), ('Cepat Pulang', 'Cepat Pulang')], max_length=20, null=True),
        ),
    ]
