# Generated by Django 5.0 on 2026-04-10 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0015_aturantoleransiketerlambatan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingMesinAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesin_id', models.CharField(max_length=255, unique=True)),
                ('pegawai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogKehadiran',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('direction', models.CharField(max_length=10)),
                ('devicename', models.CharField(max_length=255)),
                ('personname', models.CharField(max_length=255)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disiplinsdm.mappingmesinabsensi')),
            ],
        ),
    ]
