# Generated by Django 5.0 on 2026-04-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0018_alter_mappingmesinabsensi_pegawai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logkehadiran',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
