# Generated by Django 5.0 on 2026-04-11 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0019_alter_logkehadiran_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logkehadiran',
            options={'ordering': ['-datetime'], 'verbose_name': 'Log Kehadiran', 'verbose_name_plural': 'Log Kehadiran'},
        ),
        migrations.AlterModelOptions(
            name='mappingmesinabsensi',
            options={'verbose_name': 'Mapping Mesin Absensi', 'verbose_name_plural': 'Mapping Mesin Absensi'},
        ),
        migrations.AlterField(
            model_name='mappingmesinabsensi',
            name='mesin_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID Pegawai Mesin'),
        ),
        migrations.AlterField(
            model_name='mappingmesinabsensi',
            name='pegawai',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pegawai SIMADU'),
        ),
        migrations.AddConstraint(
            model_name='logkehadiran',
            constraint=models.UniqueConstraint(fields=('mapping', 'datetime', 'direction'), name='unique_log_pegawai_waktu_arah'),
        ),
    ]
