# Generated by Django 5.0 on 2026-04-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0020_alter_logkehadiran_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logkehadiran',
            index=models.Index(fields=['mapping', 'datetime'], name='disiplinsdm_mapping_f6da39_idx'),
        ),
    ]
