# Generated by Django 5.0 on 2026-06-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0021_logkehadiran_disiplinsdm_mapping_f6da39_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kehadirankegiatan',
            options={'ordering': ['-tanggal'], 'verbose_name': 'Kehadiran Kegiatan', 'verbose_name_plural': 'Kehadiran Kegiatan'},
        ),
        migrations.AddConstraint(
            model_name='kehadirankegiatan',
            constraint=models.UniqueConstraint(fields=('pegawai_id', 'tanggal'), name='unique_kehadiran_pegawai_tanggal'),
        ),
    ]
