# Generated by Django 5.0 on 2026-06-07 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0022_alter_kehadirankegiatan_options_and_more'),
        ('jenissdm', '0002_remove_listkompetensi_sifat'),
        ('strukturorg', '0002_standarinstalasi_kompetensi_wajib_parsial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daftarkegiatanpegawai',
            options={'verbose_name': 'Daftar Kegiatan Pegawai', 'verbose_name_plural': 'Daftar Kegiatan Pegawai'},
        ),
        migrations.AddConstraint(
            model_name='daftarkegiatanpegawai',
            constraint=models.UniqueConstraint(fields=('pegawai', 'kegiatan', 'bulan', 'tahun'), name='unique_rekap_kegiatan_pegawai_bulanan'),
        ),
    ]
