# Generated by Django 5.0 on 2026-06-09 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0023_alter_daftarkegiatanpegawai_options_and_more'),
        ('strukturorg', '0002_standarinstalasi_kompetensi_wajib_parsial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsensiHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('status_final', models.CharField(choices=[('HADIR', 'Hadir'), ('TK', 'Alpa / Tanpa Keterangan'), ('IZIN', 'Izin / Sakit / Cuti'), ('DINAS', 'Dinas Luar')], default='TK', max_length=10)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('bidang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strukturorg.bidang', verbose_name='Bidang / Bagian')),
                ('instalasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strukturorg.unitinstalasi', verbose_name='Instalasi / Ruangan')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_bidang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strukturorg.subbidang', verbose_name='Tim Kerja / Sub Bagian')),
                ('unor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strukturorg.unitorganisasi', verbose_name='Unit Organisasi')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='LogAktivitasAbsen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('DATANG', 'Absen Datang'), ('APEL', 'Apel Pagi'), ('PULANG', 'Absen Pulang'), ('ISHOMA_OUT', 'Keluar Istirahat'), ('ISHOMA_IN', 'Masuk Istirahat')], max_length=15)),
                ('waktu', models.DateTimeField()),
                ('status_ketepatan', models.CharField(blank=True, max_length=50, null=True)),
                ('devicename', models.CharField(blank=True, max_length=50, null=True)),
                ('absensi_harian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='disiplinsdm.absensiharian')),
                ('alasan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disiplinsdm.alasantidakhadir')),
            ],
            options={
                'ordering': ['waktu'],
            },
        ),
        migrations.AddIndex(
            model_name='absensiharian',
            index=models.Index(fields=['tanggal', 'unor'], name='disiplinsdm_tanggal_0cf22b_idx'),
        ),
        migrations.AddIndex(
            model_name='absensiharian',
            index=models.Index(fields=['tanggal', 'bidang'], name='disiplinsdm_tanggal_e7ef75_idx'),
        ),
        migrations.AddIndex(
            model_name='absensiharian',
            index=models.Index(fields=['tanggal', 'sub_bidang'], name='disiplinsdm_tanggal_5ba46a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='absensiharian',
            unique_together={('pegawai', 'tanggal')},
        ),
    ]
