# Generated by Django 5.0 on 2026-06-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0024_absensiharian_logaktivitasabsen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensiharian',
            name='status_final',
            field=models.CharField(choices=[('', 'Belum Presensi'), ('HADIR', 'Hadir'), ('TK', 'Alpa / Tanpa Keterangan'), ('IZIN', 'Izin / Sakit / Cuti'), ('DINAS', 'Dinas Luar')], default='', max_length=10),
        ),
    ]
