# Generated by Django 5.0 on 2026-07-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disiplinsdm', '0026_alter_absensiharian_status_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensiharian',
            name='status_final',
            field=models.CharField(choices=[('', 'Belum Presensi'), ('HADIR', 'Hadir'), ('ALPA', 'Alpa / Tanpa Keterangan'), ('IZIN', 'Izin / Sakit / Cuti'), ('DINAS', 'Dinas Luar'), ('LIBUR', 'Libur')], default='', max_length=10),
        ),
    ]
