"""
Django settings for sisdm project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from tkinter import FALSE
from django.contrib import messages
from decouple import config
from .scopes import Scopes

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%jc$sjzf58i)dhokb41uoqs%!j%xjkin6cd@f@#xxh3ei8yw*e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'crispy_forms',
    'crispy_bootstrap4',
    'rest_framework',
    'chartjs',
    'tinymce',
    'hitcount',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'oauth2_provider',
    'django_q',

    'myaccount',
    'dokumen',
    'strukturorg',
    'jenissdm',
    'layanan',
    'file_dokumen',
    'dashboard',
    'disiplinsdm',
    'informasi',
    'lapor',
]

AUTH_USER_MODEL = 'myaccount.Users'

# Kontak publik yang ditampilkan pada halaman Kebijakan Privasi. Isi variabel
# PRIVACY_CONTACT_EMAIL di environment production dengan alamat resmi pengelola.
PRIVACY_CONTACT_EMAIL = config('PRIVACY_CONTACT_EMAIL', default='')

# Integrasi Bot Telegram untuk pemulihan password. Rahasia hanya disimpan di
# environment dan tidak boleh ditulis langsung ke source code.
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_BOT_USERNAME = config('TELEGRAM_BOT_USERNAME', default='')
TELEGRAM_WEBHOOK_SECRET = config('TELEGRAM_WEBHOOK_SECRET', default='')
TELEGRAM_PUBLIC_BASE_URL = config(
    'TELEGRAM_PUBLIC_BASE_URL',
    default='http://127.0.0.1:8000',
).rstrip('/')
TELEGRAM_RESET_COOLDOWN = 60
PASSWORD_RESET_TIMEOUT = 30 * 60
SIP_EXPIRY_REMINDER_MONTHS = config(
    'SIP_EXPIRY_REMINDER_MONTHS',
    default=6,
    cast=int,
)
# Menggantikan ACCOUNT_AUTHENTICATION_METHOD
# Gunakan format baru ini:
ACCOUNT_SIGNUP_FIELDS = ['email*']

# Pastikan juga pengaturan login method sudah menggunakan format set:
ACCOUNT_LOGIN_METHODS = {'email'}

# Karena Anda tidak menggunakan username:
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]


ROOT_URLCONF = 'sisdm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.menu_riwayat_sdm',
                'dashboard.context_processors.menu_layanan_sdm',
                'dashboard.context_processors.notifikasi_layanan',
                'dashboard.context_processors.runningtext',
                'dokumen.context_processors.document_quick_navigation',
                'dokumen.context_processors.document_admin_selected_employee',
            ],
        },
    },
]

WSGI_APPLICATION = 'sisdm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DBNAME'),
        'USER': config('DBUSER'),
        'PASSWORD': config('DBPASSWORD'),
        'HOST': config('DBHOST'),
        'PORT': config('DBPORT'),
        'OPTIONS': { 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'", },
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    # 1. Standar Django (Penting agar login manual tetap jalan)
    'django.contrib.auth.backends.ModelBackend',

    # 2. Django OAuth Toolkit Backend
    'oauth2_provider.backends.OAuth2Backend',

    # 3. Allauth Backend (Untuk Google Login)
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# Agar Allauth tidak membuat user baru secara otomatis di level dasar
SOCIALACCOUNT_ADAPTER = 'myaccount.adapters.RestrictToExistingUserAdapter'
LOGIN_REDIRECT_URL = '/accounts/sso/'

SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_SESSION_STORE = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # Google memverifikasi kepemilikan email. Izinkan email tersebut
        # mengautentikasi user lokal yang sudah terdaftar dan hubungkan akun
        # sosialnya agar login berikutnya menggunakan identitas Google (sub).
        'EMAIL_AUTHENTICATION': True,
        'EMAIL_AUTHENTICATION_AUTO_CONNECT': True,
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKCE_ENABLED': True,
    },
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'id'

USE_I18N = True

USE_TZ = False
TIME_ZONE = 'Asia/Makassar'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'

if DEBUG:
    STATICFILES_DIRS = [
        BASE_DIR / 'static'
    ]
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    STATIC_ROOT='/var/www/html/prod/static/'
    MEDIA_ROOT = '/var/www/html/prod/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# USE_THOUSAND_SEPARATOR = True

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

X_FRAME_OPTIONS = 'SAMEORIGIN'

ALLOW_CUTI_TUNDA = True

TINYMCE_DEFAULT_CONFIG = {
    "height": "320px",
    #"width": "960px",
    "menubar": "file edit view insert format tools table help",
    "plugins": "advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code "
    "fullscreen insertdatetime media table paste code help wordcount spellchecker",
    "toolbar": "undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft "
    "aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor "
    "backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | "
    "fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | "
    "a11ycheck ltr rtl | showcomments addcomment code",
    "custom_undo_redo_levels": 10,
    #"language": "es_ES",  # To force a specific language instead of the Django current language.
}

# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'file': {
#             'level': 'ERROR',
#             'class': 'logging.FileHandler',
#             'filename': '/home/mandalikahospital/sisdm_upload/error.log',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'level': 'ERROR',
#             'propagate': True,
#         },
#     },
# }



"""
cara menampilkan logging di veiw
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/path/to/your/logfile.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
"""

APP_VISUAL = {
    "simadu": {
        "icon": "fas fa-users-cog",
        "bg_class": "bg-gradient-to-br from-indigo-500 to-indigo-600",
        "category": "Kepegawaian",
    },
    "remun": {
        "icon": "fas fa-coins",
        "bg_class": "bg-gradient-to-br from-emerald-500 to-teal-600",
        "category": "Keuangan",
    },
    "simrs": {
        "icon": "fas fa-hospital",
        "bg_class": "bg-gradient-to-br from-blue-500 to-teal-600",
        "category": "Rekam Medis",
    },
    "admin_epasien": {
        "icon": "fas fa-user-injured", 
        "bg_class": "bg-gradient-to-br from-cyan-500 to-blue-600",
        "category": "Admin Epasien",
    },
    "koperasi": {
        "icon": "fas fa-balance-scale", # Diambil dari simbol timbangan pada logo Koperasi
        "bg_class": "bg-gradient-to-br from-amber-500 to-orange-600",
        "category": "Koperasi & Syariah",
    },
    # tambahkan aplikasi lain di sini
}

SSO_CLIENTS = {
    "simadu": {
        "label": "SIMADU",
        "type": "local",  # login internal SIMADU
        "dashboard": "/",
        "client_id": None,  # tidak perlu client_id untuk aplikasi lokal
        "dashboard_absensi": "/dashboard-absensi/",
        "login_url":None,
    },
    "remun": {
        "label": "REMUNERASI",
        "type": "oauth_client",
        # ini DIDAPAT dari DOT Application untuk REMUN (client_id + redirect_uri)
        "client_id": config("CLIENT_ID_REMUN"),
        "redirect_uri": "http://127.0.0.1:8001/callback/",
        "login_url":None,
        "scopes": "read:pegawai",
    },
    "simrs": {
        "label": "SIMRS",
        "type": "oauth_client",
        # ini DIDAPAT dari DOT Application untuk SIMRS (client_id + redirect_uri)
        "client_id": config("SIMRS_CLIENT_ID"),
        "redirect_uri": "http://127.0.0.1:8002/callback/",
        "login_url":None,
        "scopes": "read:rm_read write:rm_write",
    },
    "admin_epasien": {
        "label": "EPASIEN",
        "type": "oauth_client",
        "client_id": config("EPASIEN_CLIENT_ID"),
        "redirect_uri": "http://127.0.0.1:8003/callback/",
        "login_url": "http://127.0.0.1:8005/admin-web/sso/login/",
        "scopes": "read:pasien",
    },
    "koperasi": {
        "label": "KOPERASI",
        "type": "oauth_client",
        "client_id": config("KOPERASI_CLIENT_ID"),
        "redirect_uri": "http://127.0.0.1:3000/api/auth/callback/django-oauth2",
        "login_url":None,
        "scopes": "read:koperasi",
    },
    # tambah aplikasi lain tinggal copy ini
}
SSO_AUTH_BASE = "http://127.0.0.1:8000"  # base SIMADU sendiri
PRESENSI_BASE_URL = "http://127.0.0.1:5000"  # base Flask Bridge untuk presensi

OAUTH2_PROVIDER = {
    "ACCESS_TOKEN_EXPIRE_SECONDS": 3600,
    "REFRESH_TOKEN_EXPIRE_SECONDS": 7 * 24 * 3600,
    "SCOPES": Scopes.as_choices(),
    # 'OIDC_ENABLED': True,
    # 'INTROSPECTION_REQUIRE_CLIENT_CREDENTIALS': True,
}

# "SCOPES": {
#     "read_pegawai": "Read basic data",
#     "profile_pegawai": "Read user profile",
#     'read_attlog': 'Melihat data absensi',
#     'sync_attlog': 'Menandai data sudah sinkron',
#     'manage_attlog': 'Menghapus atau memodifikasi data',
# }


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # pakai DB 1 untuk cache/session
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

SESSION_COOKIE_NAME="simadu_sessionid"
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
# pilih TRUE untuk produksi agar cookie hanya dikirim via HTTPS, tapi untuk testing di localhost biarkan False
SESSION_COOKIE_SECURE=False

Q_CLUSTER = {
    'name': 'simadu',
    'workers': 8,
    'recycle': 500,
    'timeout': 60,
    'compress': True,
    'save_limit': 250,
    'queue_limit': 500,
    'cpu_affinity': 1,
    'label': 'Django Q2',
    'redis': {
        'host': '127.0.0.1',
        'port': 6379,
        'db': 0, },
    'ALT_CLUSTERS': {
        'long': {
            'timeout': 3000,
            'retry': 3600,
            'max_attempts': 2,
        },
        'short': {
            'timeout': 10,
            'max_attempts': 1,
        },
    }
}
