# Generated by Django 5.0 on 2024-06-20 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
                ('is_user', models.BooleanField(default=False, verbose_name='officer')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kelamin', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilAdmin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_admin', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilSDM',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('no_hp', models.CharField(max_length=20, verbose_name='No HP/Telp.')),
                ('tmp_lahir', models.CharField(blank=True, max_length=15, verbose_name='Tempat Lahir')),
                ('tgl_lahir', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('nm_ibu', models.CharField(blank=True, max_length=40, verbose_name='Nama Ibu')),
                ('alamat', models.CharField(blank=True, max_length=200)),
                ('gol_darah', models.CharField(blank=True, max_length=2)),
                ('email_pribadi', models.EmailField(max_length=254)),
                ('pendidikan', models.CharField(blank=True, choices=[('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('DI', 'DI'), ('DII', 'DII'), ('DIII', 'DIII'), ('DIV', 'DIV'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=50)),
                ('gelar_depan', models.CharField(blank=True, max_length=20)),
                ('gelar_belakang', models.CharField(blank=True, max_length=25)),
                ('agama', models.CharField(blank=True, max_length=12)),
                ('stts_nikah', models.CharField(blank=True, choices=[('Belum Menikah', 'Belum Menikah'), ('Menikah', 'Menikah'), ('Duda', 'Duda'), ('Janda', 'Janda')], max_length=13, verbose_name='Status Nikah')),
                ('nip', models.CharField(blank=True, max_length=18)),
                ('no_ktp', models.CharField(blank=True, max_length=16)),
                ('no_npwp', models.CharField(blank=True, max_length=30)),
                ('no_jkn', models.CharField(blank=True, max_length=12)),
                ('no_jkk_taspen', models.CharField(blank=True, max_length=16, verbose_name='Nomor JKK/Taspen')),
                ('no_rek_gaji', models.CharField(blank=True, max_length=50, verbose_name='Rekening Gaji')),
                ('file_ktp', models.FileField(blank=True, upload_to='profil/ktp/', verbose_name='KTP')),
                ('file_npwp', models.FileField(blank=True, upload_to='profil/npwp/', verbose_name='NPWP')),
                ('file_jkn', models.FileField(blank=True, upload_to='profil/jkn/', verbose_name='BPJS')),
                ('file_taspen', models.FileField(blank=True, upload_to='profil/jkk_taspen/', verbose_name='BPJSTK/Taspen')),
                ('file_rek', models.FileField(blank=True, upload_to='profil/rekening/', verbose_name='Rekening')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profil/foto/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
