# Generated by Django 5.0 on 2024-06-20 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myaccount', '0001_initial'),
        ('strukturorg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiladmin',
            name='bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.bidang'),
        ),
        migrations.AddField(
            model_name='profiladmin',
            name='instalasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitinstalasi'),
        ),
        migrations.AddField(
            model_name='profiladmin',
            name='sub_bidang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.subbidang'),
        ),
        migrations.AddField(
            model_name='profiladmin',
            name='unor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strukturorg.unitorganisasi'),
        ),
        migrations.AddField(
            model_name='profilsdm',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myaccount.gender', verbose_name='Jenis Kelamin'),
        ),
    ]
