# Generated by Django 5.0 on 2024-07-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilsdm',
            name='no_jkn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profilsdm',
            name='no_npwp',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
