# Generated by Django 5.0 on 2024-07-21 20:12

import myaccount.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_alter_profilsdm_no_jkn_alter_profilsdm_no_npwp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='users',
            name='is_guest',
            field=models.BooleanField(default=False, verbose_name='tamu'),
        ),
        migrations.AlterField(
            model_name='profilsdm',
            name='file_jkn',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='profil/jkn/', validators=[myaccount.models.validate_file_size], verbose_name='BPJS'),
        ),
        migrations.AlterField(
            model_name='profilsdm',
            name='file_ktp',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='profil/ktp/', validators=[myaccount.models.validate_file_size], verbose_name='KTP'),
        ),
        migrations.AlterField(
            model_name='profilsdm',
            name='file_npwp',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='profil/npwp/', validators=[myaccount.models.validate_file_size], verbose_name='NPWP'),
        ),
        migrations.AlterField(
            model_name='profilsdm',
            name='file_rek',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='profil/rekening/', validators=[myaccount.models.validate_file_size], verbose_name='Rekening'),
        ),
        migrations.AlterField(
            model_name='profilsdm',
            name='file_taspen',
            field=models.FileField(blank=True, help_text='Ukuran maksimal file 2.5MB', upload_to='profil/jkk_taspen/', validators=[myaccount.models.validate_file_size], verbose_name='BPJSTK/Taspen'),
        ),
        migrations.AlterField(
            model_name='profilsdm',
            name='foto',
            field=models.ImageField(blank=True, help_text='Ukuran maksimal file 2.5MB', null=True, upload_to='profil/foto/', validators=[myaccount.models.validate_file_size]),
        ),
    ]
