# Generated by Django 5.0 on 2024-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0004_remove_users_is_admin_users_is_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilsdm',
            name='nip',
            field=models.CharField(blank=True, max_length=18, unique=True),
        ),
    ]
