# Generated by Django 5.0 on 2024-08-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0005_alter_profilsdm_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilsdm',
            name='tmp_lahir',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tempat Lahir'),
        ),
    ]
