# Generated by Django 5.0 on 2025-07-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0006_alter_profilsdm_tmp_lahir'),
        ('strukturorg', '0002_standarinstalasi_kompetensi_wajib_parsial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiladmin',
            name='instalasi',
        ),
        migrations.AddField(
            model_name='profiladmin',
            name='instalasi',
            field=models.ManyToManyField(blank=True, null=True, to='strukturorg.unitinstalasi'),
        ),
    ]
