# Generated by Django 5.0 on 2025-07-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0007_remove_profiladmin_instalasi_profiladmin_instalasi'),
        ('strukturorg', '0002_standarinstalasi_kompetensi_wajib_parsial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiladmin',
            name='instalasi',
            field=models.ManyToManyField(blank=True, to='strukturorg.unitinstalasi'),
        ),
    ]
