# Generated by Django 5.0 on 2025-08-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0008_alter_profiladmin_instalasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilsdm',
            name='is_dokter_spesialis',
            field=models.BooleanField(default=False, verbose_name='Dokter Spesialis?'),
        ),
    ]
