# Generated by Django 5.0 on 2025-12-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0009_profilsdm_is_dokter_spesialis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilsdm',
            name='pendidikan',
            field=models.CharField(blank=True, choices=[('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('DI', 'DI'), ('DII', 'DII'), ('DIII', 'DIII'), ('DIIIK', 'DIII Kesehatan'), ('DIV', 'DIV'), ('DIVK', 'DIV Kesehatan'), ('S1', 'S1'), ('S1K', 'S1 Kesehatan'), ('S1P/DIVP', 'S1 Profesi/DIV Profesi'), ('S2', 'S2'), ('S2K', 'S2 Kesehatan'), ('S3', 'S3'), ('SPES', 'Spesialis Dokter/Dokter Gigi'), ('SUBSPES', 'Sub Spesialis Dokter/Dokter Gigi')], max_length=50),
        ),
    ]
