# Generated by Django 5.0 on 2026-05-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0010_alter_profilsdm_pendidikan'),
        ('strukturorg', '0002_standarinstalasi_kompetensi_wajib_parsial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiladmin',
            name='is_pejabat',
            field=models.BooleanField(default=False, verbose_name='Menjabat?'),
        ),
        migrations.RemoveField(
            model_name='profiladmin',
            name='bidang',
        ),
        migrations.RemoveField(
            model_name='profiladmin',
            name='sub_bidang',
        ),
        migrations.RemoveField(
            model_name='profiladmin',
            name='unor',
        ),
        migrations.AddField(
            model_name='profiladmin',
            name='bidang',
            field=models.ManyToManyField(blank=True, to='strukturorg.bidang'),
        ),
        migrations.AddField(
            model_name='profiladmin',
            name='sub_bidang',
            field=models.ManyToManyField(blank=True, to='strukturorg.subbidang'),
        ),
        migrations.AddField(
            model_name='profiladmin',
            name='unor',
            field=models.ManyToManyField(blank=True, to='strukturorg.unitorganisasi'),
        ),
    ]
