# Generated by Django 5.0 on 2026-07-27 15:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myaccount', '0016_accountregistration'),
        ('strukturorg', '0004_pejabatstruktur_jenis_penugasan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminScopeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('global', 'Seluruh organisasi'), ('instansi_daerah', 'Instansi daerah'), ('satuan_kerja_induk', 'Satuan kerja induk'), ('unit_organisasi', 'Unit organisasi'), ('bidang', 'Bidang'), ('sub_bidang', 'Sub bidang'), ('unit_instalasi', 'Unit instalasi')], max_length=24)),
                ('scope_key', models.CharField(editable=False, max_length=64)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bidang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_scope_assignments', to='strukturorg.bidang')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_scope_assignments', to='auth.group', verbose_name='Peran admin')),
                ('instansi_daerah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_scope_assignments', to='strukturorg.instansidaerah')),
                ('satuan_kerja_induk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_scope_assignments', to='strukturorg.satuankerjainduk')),
                ('sub_bidang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_scope_assignments', to='strukturorg.subbidang')),
                ('unit_instalasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_scope_assignments', to='strukturorg.unitinstalasi')),
                ('unit_organisasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_scope_assignments', to='strukturorg.unitorganisasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_scope_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cakupan admin',
                'verbose_name_plural': 'Cakupan admin',
                'ordering': ('user', 'group', 'scope_type', 'scope_key'),
            },
        ),
        migrations.AddConstraint(
            model_name='adminscopeassignment',
            constraint=models.UniqueConstraint(fields=('user', 'group', 'scope_key'), name='uniq_admin_role_scope'),
        ),
    ]
