# Generated by Django 5.0 on 2026-09-04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myaccount', '0018_create_admin_sso_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('atasan_langsung', 'Atasan langsung'), ('staf_pendukung', 'Staf pendukung/koordinasi')], default='staf_pendukung', max_length=24, verbose_name='Jenis hubungan')),
                ('valid_from', models.DateField(default=datetime.date.today, verbose_name='TMT')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Tanggal berakhir')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Keterangan')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('active_slot', models.BooleanField(editable=False, null=True)),
                ('direct_supervisor_slot', models.BooleanField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordination_subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Koordinator/atasan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordination_supervisors', to=settings.AUTH_USER_MODEL, verbose_name='Pegawai/staf')),
            ],
            options={
                'verbose_name': 'Penugasan koordinasi',
                'verbose_name_plural': 'Penugasan koordinasi',
                'ordering': ('coordinator', 'employee', 'relation_type'),
            },
        ),
        migrations.AddConstraint(
            model_name='coordinationassignment',
            constraint=models.UniqueConstraint(fields=('coordinator', 'employee', 'relation_type', 'active_slot'), name='uniq_active_coordination_pair'),
        ),
        migrations.AddConstraint(
            model_name='coordinationassignment',
            constraint=models.UniqueConstraint(fields=('employee', 'direct_supervisor_slot'), name='uniq_active_direct_supervisor'),
        ),
    ]
