# Generated by Django 5.0 on 2024-09-06 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layanan', '0008_layananusulandiklat_biaya'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSPTDiklat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dasar_pelaksanaan', models.TextField(blank=True)),
                ('tujuan_pelaksanaan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diklat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.layananusulandiklat')),
            ],
        ),
    ]
