# Generated by Django 5.0 on 2024-06-20 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisSDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_sdm', models.CharField(blank=True, choices=[('Nakes', 'Nakes'), ('Non Nakes', 'Non Nakes')], max_length=25)),
                ('jenis_sdm', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('warna_card', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProfesiSDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListKompetensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompetensi', models.CharField(max_length=200)),
                ('sifat', models.CharField(blank=True, choices=[('Wajib', 'Wajib'), ('Pendukung', 'Pendukung')], max_length=10)),
                ('jenis_sdm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jenissdm.jenissdm')),
            ],
        ),
        migrations.AddField(
            model_name='jenissdm',
            name='profesi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jenissdm.profesisdm'),
        ),
    ]
