# Generated by Django 5.0 on 2024-08-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jenissdm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listkompetensi',
            name='sifat',
        ),
    ]
